'use client';

import { useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams, useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Check, Clock, Loader2, Trophy, Wifi, Zap, Sparkles, X, Users, ArrowLeft } from 'lucide-react';

type Quiz = { id:string; title:string; status:string; current_question:number; question_started_at?:string|null; game_code?:string|null };
type Q = { id:string; question_order:number; question:string; option_a:string; option_b:string; option_c:string; option_d:string; correct_answer:string; time_limit_seconds:number };
type Player = { id:string; nickname:string; score:number; total_response_time_ms:number; correct_answers:number };
const url = (process.env.NEXT_PUBLIC_SUPABASE_URL || '').replace(/\/$/, '');
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const shapes = [
  { letter:'A', shape:'triangle', className:'bg-red-500' },
  { letter:'B', shape:'diamond', className:'bg-blue-500' },
  { letter:'C', shape:'circle', className:'bg-yellow-500' },
  { letter:'D', shape:'square', className:'bg-green-500' }
] as const;
const STATUS_ORDER: Record<string, number> = { draft:0, lobby:1, question_reveal:2, answering:3, results:4, intermission:5, finished:6 };
function sid(){try{const u=JSON.parse(localStorage.getItem('current_user')||'{}');return String(u.student_id??u.id??u.user_id??u.uid??'').trim()||null}catch{return null}}
async function api(path:string,opts:RequestInit={}){if(!url||!key)throw new Error('Live quiz connection is not configured on this deployment.');const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),10000);try{const r=await fetch(`${url}/rest/v1/${path}`,{...opts,signal:controller.signal,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(opts.headers||{})},cache:'no-store'});const text=await r.text();if(!r.ok)throw new Error(text||`Request failed (${r.status})`);return text.trim()?JSON.parse(text):null}catch(e){if(e instanceof DOMException&&e.name==='AbortError')throw new Error('Could not connect to the live quiz server. Check the connection and try again.');throw e}finally{window.clearTimeout(timeout)}}
function fmt(ms:number|null|undefined){return ms==null||ms<0?'—':`${(ms/1000).toFixed(2)}s`}
function Shape({type}:{type:string}){return <span className="flex size-24 items-center justify-center sm:size-32"><span className={`block size-20 sm:size-28 ${type==='triangle'?'[clip-path:polygon(50%_0%,100%_100%,0%_100%)':type==='diamond'?'rotate-45 rounded-lg':type==='circle'?'rounded-full':'rounded-lg'} bg-white shadow-md`}/></span>}
export default function LiveQuizGame(){
 const params=useParams<{code:string}>(),search=useSearchParams(),router=useRouter();const code=String(params?.code||'').toUpperCase(),nickname=search.get('name')||'Player';const source=search.get('from');const returnPath=source==='dashboard'?'/dashboard/student':source==='signup'?'/sign-up':source==='signin'?'/':'/';const returnLabel=source==='dashboard'?'Back to Dashboard':source==='signup'?'Back to Sign Up':'Back to Sign In';
 const[quiz,setQuiz]=useState<Quiz|null>(null),[questions,setQuestions]=useState<Q[]>([]),[player,setPlayer]=useState<Player|null>(null),[answer,setAnswer]=useState(''),[answered,setAnswered]=useState(false),[result,setResult]=useState<boolean|null>(null),[responseTime,setResponseTime]=useState<number|null>(null),[remaining,setRemaining]=useState(30),[error,setError]=useState(''),[joining,setJoining]=useState(false),[submitting,setSubmitting]=useState(false),[ranking,setRanking]=useState<Player[]>([]),[loadingTimedOut,setLoadingTimedOut]=useState(false);const flight=useRef(false),stateKey=useRef('');
 async function load(){if(flight.current)return;flight.current=true;setError('');try{if(!code)throw new Error('No live quiz code was found in this link.');const rows=await api(`live_quizzes?game_code=eq.${encodeURIComponent(code)}&select=*`);if(!rows?.[0])throw new Error('Game not found.');const qz=rows[0] as Quiz;setQuiz(prev=>{if(!prev)return qz;const prevIndex=prev.current_question,liveIndex=qz.current_question;if(liveIndex<prevIndex)return prev;const sameQuestion=prevIndex===liveIndex;const prevRank=STATUS_ORDER[prev.status]??0,liveRank=STATUS_ORDER[qz.status]??0;if(sameQuestion&&liveRank<prevRank)return prev;return prev.status===qz.status&&sameQuestion&&prev.question_started_at===qz.question_started_at?prev:qz});const[qs,ps]=await Promise.all([api(`live_quiz_questions?quiz_id=eq.${encodeURIComponent(qz.id)}&select=*&order=question_order.asc`),api(`live_quiz_players?quiz_id=eq.${encodeURIComponent(qz.id)}&nickname=eq.${encodeURIComponent(nickname)}&select=*`)]);if(Array.isArray(qs))setQuestions(qs);if(ps?.[0])setPlayer(ps[0]);const q=Array.isArray(qs)?qs[qz.current_question] as Q|undefined:undefined;if(q&&(qz.status==='results'||qz.status==='intermission')&&ps?.[0]){const ar=await api(`live_quiz_answers?quiz_id=eq.${encodeURIComponent(qz.id)}&question_id=eq.${encodeURIComponent(q.id)}&player_id=eq.${encodeURIComponent(ps[0].id)}&select=answer,correct,response_time_ms&limit=1`);if(ar?.[0]){setAnswer(ar[0].answer||'');setResult(Boolean(ar[0].correct));setResponseTime(ar[0].response_time_ms??null);setAnswered(true)}}if(qz.status==='finished'){const all=await api(`live_quiz_players?quiz_id=eq.${encodeURIComponent(qz.id)}&select=*&order=correct_answers.desc,total_response_time_ms.asc`);setRanking(all||[])}setLoadingTimedOut(false)}catch(e){setError(e instanceof Error?e.message:'Could not load quiz.')}finally{flight.current=false}}
 useEffect(()=>{setLoadingTimedOut(false);const timeout=window.setTimeout(()=>setLoadingTimedOut(true),12000);void load();const t=window.setInterval(()=>void load(),700);return()=>{window.clearTimeout(timeout);window.clearInterval(t)}},[code,nickname]);
 const idx=quiz?.current_question??-1,q=questions[idx],answering=quiz?.status==='answering',results=quiz?.status==='results',intermission=quiz?.status==='intermission';const myRank=ranking.findIndex(p=>p.id===player?.id)+1;
 useEffect(()=>{const k=`${quiz?.id||''}:${idx}:${q?.id||''}`;if(!q||k===stateKey.current)return;stateKey.current=k;setAnswer('');setAnswered(false);setResult(null);setResponseTime(null);setSubmitting(false);setRemaining(q.time_limit_seconds||30)},[quiz?.id,idx,q?.id]);
 useEffect(()=>{if(!answering||!q)return;setRemaining(q.time_limit_seconds||30)},[answering,q?.id,q?.time_limit_seconds]);
 useEffect(()=>{if(!answering||!quiz?.question_started_at||!q)return;const start=new Date(quiz.question_started_at).getTime(),limit=(q.time_limit_seconds||30)*1000;const tick=()=>setRemaining(Math.max(0,Math.ceil((limit-(Date.now()-start))/1000)));tick();const t=window.setInterval(tick,100);return()=>window.clearInterval(t)},[answering,quiz?.question_started_at,q?.id,q?.time_limit_seconds]);
 async function join(){if(player||!quiz||joining)return;setJoining(true);setError('');try{const rows=await api('live_quiz_players',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({quiz_id:quiz.id,student_id:sid(),nickname})});setPlayer(rows?.[0]||null)}catch(e){setError(e instanceof Error?e.message:'Could not join lobby.')}finally{setJoining(false)}}
 async function submit(v:string){if(!quiz||!player||!q||answered||submitting||!answering||remaining<=0)return;const correct=v===q.correct_answer;setAnswer(v);setResult(correct);setAnswered(true);setSubmitting(true);setError('');try{const start=quiz.question_started_at?new Date(quiz.question_started_at).getTime():Date.now(),elapsed=Math.min((q.time_limit_seconds||30)*1000,Math.max(0,Date.now()-start));await api('live_quiz_answers',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({quiz_id:quiz.id,question_id:q.id,player_id:player.id,answer:v,correct,response_time_ms:elapsed,points_earned:correct?1:0})});setResponseTime(elapsed);const nextCorrect=Number(player.correct_answers||0)+(correct?1:0),nextTime=Number(player.total_response_time_ms||0)+elapsed,nextScore=Number(player.score||0)+(correct?1:0);const rows=await api(`live_quiz_players?id=eq.${encodeURIComponent(player.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({correct_answers:nextCorrect,total_response_time_ms:nextTime,score:nextScore})});setPlayer(rows?.[0]||{...player,correct_answers:nextCorrect,total_response_time_ms:nextTime,score:nextScore})}catch(e){setAnswered(false);setError(e instanceof Error?e.message:'Could not submit answer.')}finally{setSubmitting(false)}}
 if(error&&!quiz)return <main className="flex min-h-screen items-center justify-center bg-muted/30 p-5"><Card className="w-full max-w-md rounded-3xl"><CardContent className="p-8 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-destructive/10"><X className="size-7 text-destructive"/></div><h1 className="mt-5 text-2xl font-black">Unable to join game</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p><Button className="mt-5 rounded-xl" onClick={()=>router.push('/join')}>Back to Join</Button></CardContent></Card></main>;
 if(!quiz)return <main className="flex min-h-screen items-center justify-center bg-muted/30"><div className="flex flex-col items-center gap-4 text-center"><Loader2 className="size-9 animate-spin text-primary"/><p className="text-sm font-semibold text-muted-foreground">Connecting to live quiz…</p>{loadingTimedOut&&<><p className="max-w-xs text-xs text-muted-foreground">The connection is taking longer than expected.</p><Button variant="outline" className="rounded-xl" onClick={()=>{setLoadingTimedOut(false);void load()}}>Try again</Button></>}</div></main>;
 if(error&&!q)return <main className="flex min-h-screen items-center justify-center bg-muted/30 p-5"><Card className="w-full max-w-md rounded-3xl"><CardContent className="p-8 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-destructive/10"><X className="size-7 text-destructive"/></div><h1 className="mt-5 text-2xl font-black">Connection problem</h1><p className="mt-2 text-sm text-muted-foreground">{error}</p><Button className="mt-5 rounded-xl" onClick={()=>{setError('');void load()}}>Try again</Button></CardContent></Card></main>;
 if(!player)return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-muted/30 px-5 py-8 sm:py-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,hsl(var(--primary)/.14),transparent_55%)]"/><Card className="relative w-full max-w-lg overflow-hidden rounded-[2rem] border-0 shadow-2xl"><div className="bg-primary px-7 py-9 text-center text-primary-foreground"><div className="mx-auto flex size-16 items-center justify-center rounded-2xl bg-white/15"><Zap className="size-8"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.3em] opacity-80">EduQuizLabs Live</p><h1 className="mt-2 text-3xl font-black">{quiz.title}</h1></div><CardContent className="space-y-5 p-7 sm:p-8"><div className="rounded-2xl bg-muted/60 p-4 text-center"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Playing as</p><p className="mt-1 text-xl font-black">{nickname}</p></div><Button size="lg" className="h-12 w-full rounded-xl font-black" onClick={join} disabled={joining}>{joining?'Joining…':'Join Lobby'}<Users className="ml-2 size-5"/></Button>{error&&<p className="text-center text-sm font-medium text-destructive">{error}</p>}<button onClick={()=>router.push('/join')} className="mx-auto flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Change game code</button></CardContent></Card></main>;
 if(quiz.status==='lobby')return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-muted/30 px-5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,hsl(var(--primary)/.15),transparent_55%)]"/><div className="relative w-full max-w-2xl text-center"><div className="mx-auto flex size-24 items-center justify-center rounded-[2rem] bg-primary text-primary-foreground shadow-xl"><Wifi className="size-11"/></div><p className="mt-7 text-[11px] font-black uppercase tracking-[.35em] text-primary">You're connected</p><h1 className="mt-2 text-5xl font-black tracking-tight sm:text-7xl">You're in!</h1><div className="mx-auto mt-6 max-w-md rounded-3xl border bg-card/80 p-6 shadow-lg backdrop-blur"><p className="text-sm text-muted-foreground">Waiting for your teacher to start</p><div className="mt-5 flex items-center justify-center gap-2 text-sm font-bold"><span className="size-2 animate-pulse rounded-full bg-green-500"/>Live connection</div></div></div></main>;
 if(quiz.status==='finished')return <main className="min-h-screen bg-muted/30 px-4 py-8 sm:py-12"><div className="mx-auto max-w-2xl"><Card className="overflow-hidden rounded-[2rem] border-0 shadow-2xl"><div className="bg-primary px-6 py-10 text-center text-primary-foreground"><Trophy className="mx-auto size-14"/><p className="mt-4 text-[11px] font-black uppercase tracking-[.3em] opacity-80">Final results</p><h1 className="mt-2 text-4xl font-black">Quiz Finished!</h1><div className="mx-auto mt-6 max-w-sm rounded-3xl bg-white/15 px-6 py-5 backdrop-blur"><p className="text-xs font-black uppercase tracking-[.25em] opacity-80">Your final place</p><p className="mt-1 text-6xl font-black">{myRank>0?`#${myRank}`:'—'}</p><p className="mt-1 text-sm font-semibold opacity-90">out of {ranking.length} {ranking.length===1?'player':'players'}</p></div></div><CardContent className="p-5 pt-10 sm:p-7 sm:pt-12"><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted/60 p-5 text-center"><b className="text-3xl font-black">{player.correct_answers}</b><p className="mt-1 text-xs font-bold uppercase text-muted-foreground">Correct</p></div><div className="rounded-2xl bg-muted/60 p-5 text-center"><b className="text-3xl font-black">{fmt(player.total_response_time_ms)}</b><p className="mt-1 text-xs font-bold uppercase text-muted-foreground">Total time</p></div></div><div className="mt-6 space-y-2">{ranking.map((p,i)=><div key={p.id} className={`flex items-center gap-3 rounded-2xl border p-4 ${p.id===player.id?'border-primary bg-primary/10':''}`}><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-black">{i+1}</span><span className="min-w-0 flex-1 truncate font-bold">{p.nickname}</span><span className="text-xs font-bold text-muted-foreground">{p.correct_answers} correct</span></div>)}</div><Button className="mt-6 h-11 w-full rounded-xl" onClick={()=>router.push(returnPath)}>{returnLabel}</Button></CardContent></Card></div></main>;
 if(results&&result!==null)return <main className={`fixed inset-0 z-[100] flex min-h-screen items-center justify-center overflow-hidden px-5 text-white ${result===true?'bg-green-500':'bg-red-500'}`}><div className="relative w-full max-w-3xl text-center animate-in fade-in zoom-in-90 duration-500"><div className="mx-auto flex size-36 items-center justify-center rounded-[2.5rem] bg-white/20 shadow-2xl animate-in zoom-in duration-500 sm:size-48">{result?<Check className="size-24 sm:size-32"/>:<X className="size-24 sm:size-32"/>}</div><p className="mt-7 text-sm font-black uppercase tracking-[.4em]">{result?'Correct answer':'Not this time'}</p><h1 className="mt-2 text-6xl font-black sm:text-8xl">{result?'CORRECT':'WRONG'}</h1><div className="mx-auto mt-7 max-w-sm rounded-[2rem] bg-white/15 p-6 backdrop-blur"><p className="text-xs font-black uppercase tracking-[.2em] opacity-80">Response time</p><p className="mt-2 text-5xl font-black tabular-nums">{fmt(responseTime)}</p><p className="mt-3 text-sm font-semibold opacity-90">{answer?`Your answer: ${answer}`:'No answer submitted'}</p></div><p className="mt-7 text-sm font-bold opacity-75">Next question coming up…</p></div></main>;
 if(intermission)return <main className="fixed inset-0 z-[100] flex min-h-screen items-center justify-center overflow-hidden bg-background px-6 text-center"><div className="animate-in fade-in zoom-in-95 duration-500"><div className="mx-auto flex size-24 items-center justify-center rounded-[2rem] bg-primary/10"><Sparkles className="size-12 animate-pulse text-primary"/></div><p className="mt-7 text-[11px] font-black uppercase tracking-[.4em] text-primary">Intermission</p><h1 className="mt-2 text-5xl font-black tracking-tight sm:text-7xl">Get ready!</h1><p className="mt-4 text-muted-foreground">The next question is coming up.</p></div></main>;
 if(quiz.status==='question_reveal')return <main className="fixed inset-0 z-[100] flex min-h-screen items-center justify-center overflow-hidden bg-background px-6 text-center"><div className="animate-in fade-in zoom-in-95 duration-500"><div className="mx-auto flex size-24 items-center justify-center rounded-[2rem] bg-primary text-primary-foreground shadow-xl"><Zap className="size-12"/></div><p className="mt-7 text-[11px] font-black uppercase tracking-[.4em] text-primary">Question {idx+1} of {questions.length}</p><h1 className="mt-2 text-5xl font-black sm:text-7xl">Get ready!</h1><p className="mt-4 text-muted-foreground">Answers will open in a moment.</p></div></main>;
 if(!q)return <main className="flex min-h-screen items-center justify-center bg-muted/30"><Loader2 className="size-8 animate-spin text-primary"/></main>;
 const pct=Math.max(0,Math.min(100,(remaining/Math.max(1,q.time_limit_seconds||30))*100));
 return <main className="min-h-screen overflow-hidden bg-muted/30 px-3 py-3 sm:px-6 sm:py-6"><div className="mx-auto flex min-h-[calc(100vh-1.5rem)] max-w-6xl flex-col gap-4 sm:gap-6"><header className="mb-1 flex items-center justify-between rounded-2xl border bg-card px-5 py-4 shadow-sm sm:px-7 sm:py-5"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-primary">{quiz.title}</p><p className="mt-0.5 text-sm font-black">Question {idx+1} <span className="font-medium text-muted-foreground">of {questions.length}</span></p></div><div className={`flex items-center gap-2 rounded-xl px-3 py-2 text-lg font-black tabular-nums ${remaining<=5?'bg-red-500/10 text-red-600':'bg-primary/10 text-primary'}`}><Clock className="size-5"/>{remaining}s</div></header><Card className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-[2rem] border-0 shadow-xl"><CardHeader className="px-5 pb-5 pt-8 sm:px-10 sm:pb-7 sm:pt-10"><div className={`mx-auto w-fit rounded-full px-4 py-1.5 text-[10px] font-black uppercase tracking-wider ${answered?'bg-green-500/10 text-green-600':'bg-primary/10 text-primary'}`}>{answered?'Answer submitted':'Choose an answer'}</div><div className="mx-auto mt-5 h-2.5 w-full max-w-3xl overflow-hidden rounded-full bg-muted"><div className={`h-full transition-[width] duration-100 ${remaining<=5?'bg-red-500':'bg-primary'}`} style={{width:`${pct}%`}}/></div></CardHeader><CardContent className="grid min-h-0 flex-1 grid-cols-2 grid-rows-2 gap-4 p-4 sm:gap-6 sm:p-7">{shapes.map((s)=>{const selected=answer===s.letter;return <button key={s.letter} aria-label={`Answer ${s.letter}`} disabled={answered||submitting||remaining<=0} onClick={()=>submit(s.letter)} className={`group relative flex min-h-36 h-full items-center justify-center overflow-hidden rounded-[1.75rem] ${s.className} text-white shadow-lg transition duration-150 hover:-translate-y-1 hover:shadow-xl active:scale-[.98] disabled:cursor-default disabled:opacity-70 ${selected?'ring-4 ring-white/90 brightness-110':''}`}><Shape type={s.shape}/>{selected&&<Check className="absolute bottom-4 right-4 size-7"/>}</button>})}</CardContent><div className="px-5 pb-5 text-center text-xs font-medium text-muted-foreground sm:pb-6">{answered?'Answer locked in • Wait for the result':'Select a shape — you can only submit once'}</div></Card></div></main>;
}
