'use client';

import { useEffect, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Quiz={id:string;title:string;status:string;current_question:number}; type Q={id:string;question_order:number;question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:string}; type Player={id:string;nickname:string;score:number};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;const headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};
function sid(){try{const u=JSON.parse(localStorage.getItem('current_user')||'{}');return String(u.student_id??u.id??u.user_id??u.uid??'')||null;}catch{return null;}}
export default function LiveQuizGame(){const params=useParams<{code:string}>();const search=useSearchParams();const code=String(params?.code||'').toUpperCase();const nickname=search.get('name')||'Player';const [quiz,setQuiz]=useState<Quiz|null>(null),[questions,setQuestions]=useState<Q[]>([]),[player,setPlayer]=useState<Player|null>(null),[answer,setAnswer]=useState(''),[answered,setAnswered]=useState(false),[error,setError]=useState('');
 async function api(path:string,opts:RequestInit={}){const r=await fetch(`${url}/rest/v1/${path}`,{...opts,headers:{...headers,...(opts.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json();}
 async function load(){try{const qr=await api(`live_quizzes?game_code=eq.${encodeURIComponent(code)}&select=*`);if(!qr?.[0])throw new Error('Game not found.');const x=qr[0];setQuiz(x);const qs=await api(`live_quiz_questions?quiz_id=eq.${x.id}&select=*&order=question_order.asc`);setQuestions(qs||[]);const ps=await api(`live_quiz_players?quiz_id=eq.${x.id}&nickname=eq.${encodeURIComponent(nickname)}&select=*`);if(ps?.[0])setPlayer(ps[0]);}catch(e){setError(e instanceof Error?e.message:'Could not load quiz.');}}
 useEffect(()=>{load();const t=window.setInterval(load,1000);return()=>window.clearInterval(t);},[code,nickname]);
 useEffect(()=>{setAnswered(false);setAnswer('');},[quiz?.current_question]);
 async function join(){if(player||!quiz)return;try{const rows=await api('live_quiz_players',{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({quiz_id:quiz.id,student_id:sid(),nickname})});setPlayer(rows[0]);}catch(e){setError(e instanceof Error?e.message:'Could not join the lobby.');}}
 async function submit(value:string){if(!quiz||!player||answered||quiz.status!=='question')return;const q=questions[quiz.current_question];if(!q)return;setAnswer(value);setAnswered(true);try{const correct=value===q.correct_answer;const points=correct?100:0;await api('live_quiz_answers',{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({quiz_id:quiz.id,question_id:q.id,player_id:player.id,answer:value,correct,response_time_ms:null})});if(points)await api(`live_quiz_players?id=eq.${player.id}`,{method:'PATCH',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({score:player.score+points})});}catch(e){setError(e instanceof Error?e.message:'Could not submit answer.');}}
 if(error&&!quiz)return <main className="flex min-h-screen items-center justify-center px-6"><Card><CardContent className="py-10"><p className="text-destructive">{error}</p></CardContent></Card></main>;
 if(!quiz)return <main className="flex min-h-screen items-center justify-center"><p>Loading…</p></main>;
 if(!player)return <main className="flex min-h-screen items-center justify-center px-6"><Card className="w-full max-w-md text-center"><CardHeader><CardTitle>{quiz.title}</CardTitle></CardHeader><CardContent className="space-y-4"><p>Joining as <b>{nickname}</b></p><Button className="w-full" onClick={join}>Join Lobby</Button></CardContent></Card></main>;
 const q=questions[quiz.current_question];return <main className="mx-auto max-w-3xl px-6 py-8"><Card><CardHeader className="text-center"><p className="text-sm text-muted-foreground">{quiz.status==='lobby'?'Waiting for teacher…':quiz.status==='finished'?'Quiz finished':'Question '+(quiz.current_question+1)}</p><CardTitle className="text-3xl">{quiz.status==='lobby'?'Get ready!':quiz.status==='finished'?`Final score: ${player.score}`:q?.question}</CardTitle></CardHeader><CardContent>{quiz.status==='lobby'&&<p className="text-center text-muted-foreground">You are in the lobby as <b>{nickname}</b>.</p>}{quiz.status==='question'&&q&&<div className="grid gap-3 md:grid-cols-2">{['A','B','C','D'].map(x=><Button key={x} className="h-auto min-h-20 whitespace-normal p-4 text-lg" variant={answer===x?'default':'outline'} disabled={answered} onClick={()=>submit(x)}>{x}: {q[`option_${x.toLowerCase()}` as 'option_a'|'option_b'|'option_c'|'option_d']}</Button>)}</div>}{quiz.status==='question'&&answered&&<p className="mt-4 text-center text-muted-foreground">Answer locked. Waiting for the next question…</p>}{quiz.status==='finished'&&<p className="mt-3 text-center text-muted-foreground">Thanks for playing!</p>}{error&&<p className="mt-4 text-center text-sm text-destructive">{error}</p>}</CardContent></Card></main>;
}
