'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Radio, Play, Plus, Users, Trophy, Clock, MonitorPlay, Copy } from 'lucide-react';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const headers={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};
type Q={id:string;question_order:number;question:string;option_a:string;option_b:string;option_c:string;option_d:string;correct_answer:string;time_limit_seconds:number};
type Quiz={id:string;title:string;class_code:string;game_code:string|null;status:string;current_question:number;is_template:boolean};
type Player={id:string;nickname:string;score:number};
const answerColors:{letter:string;label:string;className:string}[]=[
 {letter:'A',label:'▲',className:'bg-red-500'},
 {letter:'B',label:'◆',className:'bg-blue-500'},
 {letter:'C',label:'●',className:'bg-yellow-500'},
 {letter:'D',label:'■',className:'bg-green-500'}
];
function teacherId(){try{const u=JSON.parse(localStorage.getItem('current_user')||'{}');return String(u.id??u.user_id??u.uid??'')||null;}catch{return null;}}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase();}
export default function TeacherLiveQuiz(){
 const router=useRouter();
 const [templates,setTemplates]=useState<Quiz[]>([]),[selected,setSelected]=useState<Quiz|null>(null),[quiz,setQuiz]=useState<Quiz|null>(null),[questions,setQuestions]=useState<Q[]>([]),[players,setPlayers]=useState<Player[]>([]);
 const [title,setTitle]=useState('My Live Quiz'),[classCode,setClassCode]=useState(''),[q,setQ]=useState(''),[a,setA]=useState(''),[b,setB]=useState(''),[c,setC]=useState(''),[d,setD]=useState(''),[correct,setCorrect]=useState('A'),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const current=quiz?.current_question??-1;
 async function api(path:string,opts:RequestInit={}){const r=await fetch(`${url}/rest/v1/${path}`,{...opts,headers:{...headers,...(opts.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json();}
 async function loadTemplates(){try{const id=teacherId();if(!id)return;const rows=await api(`live_quizzes?teacher_id=eq.${encodeURIComponent(id)}&is_template=eq.true&status=eq.draft&select=id,title,class_code,game_code,status,current_question,is_template&order=created_at.desc`);setTemplates(rows||[]);}catch(e){console.error(e);}}
 useEffect(()=>{loadTemplates();},[]);
 async function createTemplate(){if(!title.trim()||!classCode.trim()){setError('Enter a quiz title and class code.');return;}setLoading(true);setError('');try{const rows=await api('live_quizzes',{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({title:title.trim(),class_code:classCode.trim().toUpperCase(),teacher_id:teacherId(),game_code:null,status:'draft',is_template:true,current_question:-1})});const created=rows[0] as Quiz;setSelected(created);setQuestions([]);}catch(e){setError(e instanceof Error?e.message:'Could not create quiz.');}finally{setLoading(false);}}
 async function openTemplate(t:Quiz){setSelected(t);setError('');try{const qs=await api(`live_quiz_questions?quiz_id=eq.${t.id}&select=*&order=question_order.asc`);setQuestions(qs||[]);}catch(e){setError(e instanceof Error?e.message:'Could not load quiz.');}}
 async function add(){if(!selected||!q.trim()||![a,b,c,d].every(x=>x.trim())){setError('Fill the question and all four answers.');return;}setError('');try{const rows=await api('live_quiz_questions',{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({quiz_id:selected.id,question_order:questions.length,question:q.trim(),option_a:a.trim(),option_b:b.trim(),option_c:c.trim(),option_d:d.trim(),correct_answer:correct,time_limit_seconds:30})});setQuestions(prev=>[...prev,...rows]);setQ('');setA('');setB('');setC('');setD('');}catch(e){setError(e instanceof Error?e.message:'Could not add question.');}}
 async function launchTemplate(){if(!selected||!questions.length){setError('Add at least one question before starting.');return;}setLoading(true);setError('');try{
   const rows=await api('live_quizzes',{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({title:selected.title,class_code:selected.class_code,teacher_id:teacherId(),game_code:code(),status:'lobby',current_question:-1,is_template:false})});
   const live=rows[0] as Quiz; const cloned=await api(`live_quiz_questions?quiz_id=eq.${selected.id}&select=question_order,question,option_a,option_b,option_c,option_d,correct_answer,time_limit_seconds&order=question_order.asc`);
   for(const item of cloned||[]) await api('live_quiz_questions',{method:'POST',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({...item,quiz_id:live.id,time_limit_seconds:30})});
   setQuiz(live);setQuestions(cloned||[]);setSelected(null);
 }catch(e){setError(e instanceof Error?e.message:'Could not start live quiz.');}finally{setLoading(false);}}
 async function setStatus(status:string,index:number){if(!quiz)return;try{const rows=await api(`live_quizzes?id=eq.${quiz.id}`,{method:'PATCH',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify({status,current_question:index})});setQuiz(rows?.[0]||{...quiz,status,current_question:index});}catch(e){setError(e instanceof Error?e.message:'Could not update quiz.');}}
 async function loadLive(){if(!quiz)return;try{const p=await api(`live_quiz_players?quiz_id=eq.${quiz.id}&select=id,nickname,score&order=score.desc`);setPlayers(p||[]);const x=await api(`live_quizzes?id=eq.${quiz.id}&select=*`);if(x?.[0])setQuiz(x[0]);}catch(e){console.error(e);}}
 useEffect(()=>{if(!quiz)return;loadLive();const t=window.setInterval(loadLive,1000);return()=>window.clearInterval(t);},[quiz?.id]);
 const currentQ=questions[current];
 if(quiz){return <main className="min-h-screen bg-background px-6 py-8"><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-primary">TEACHER HOST SCREEN · SCREEN-SHARE THIS PAGE</p><h1 className="text-3xl font-bold">{quiz.title}</h1><p className="text-muted-foreground">Game code</p><p className="text-5xl font-black tracking-[0.25em]">{quiz.game_code}</p></div><Button variant="outline" onClick={()=>router.push('/dashboard/teacher')}>Exit</Button></div>
 {error&&<p className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}
 {quiz.status==='lobby'&&<Card><CardContent className="py-12 text-center"><MonitorPlay className="mx-auto mb-4 size-12"/><h2 className="text-3xl font-bold">Join at the code above</h2><p className="mt-2 text-muted-foreground">Students see only four answer shapes on their devices.</p><p className="mt-6 text-4xl font-black"><Users className="mr-2 inline size-8"/>{players.length}</p><Button className="mt-6" disabled={!questions.length} onClick={()=>setStatus('question',0)}>Start Question 1</Button></CardContent></Card>}
 {quiz.status==='question'&&currentQ&&<div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><Card className="overflow-hidden"><CardHeader className="text-center"><div className="flex items-center justify-between text-sm font-semibold"><span>QUESTION {current+1} / {questions.length}</span><span className="inline-flex items-center gap-1"><Clock className="size-4"/>30 seconds</span></div><CardTitle className="mt-8 text-4xl leading-tight">{currentQ.question}</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-4">{answerColors.map((x,i)=><div key={x.letter} className={`min-h-36 rounded-2xl ${x.className} p-6 text-white`}><div className="text-4xl font-black">{x.label}</div><p className="mt-4 text-2xl font-bold">{currentQ[`option_${x.letter.toLowerCase()}` as 'option_a'|'option_b'|'option_c'|'option_d']}</p></div>)}</div><div className="mt-6 flex justify-between"><span className="text-sm text-muted-foreground">Correct answer: {currentQ.correct_answer}</span>{current+1<questions.length?<Button onClick={()=>setStatus('question',current+1)}>Next Question</Button>:<Button onClick={()=>setStatus('finished',current)}>Finish Quiz</Button>}</div></CardContent></Card><Card><CardHeader><CardTitle>Live Leaderboard</CardTitle></CardHeader><CardContent className="space-y-2">{players.map((p,i)=><div key={p.id} className="flex items-center justify-between rounded-lg border p-3"><span className="font-semibold">{i+1}. {p.nickname}</span><span className="text-sm font-bold">{p.score} pts</span></div>)}</CardContent></Card></div>}
 {quiz.status==='finished'&&<Card><CardHeader className="text-center"><Trophy className="mx-auto size-14"/><CardTitle className="text-4xl">Final Leaderboard</CardTitle><p className="text-muted-foreground">Ranked by lowest total correct-answer time.</p></CardHeader><CardContent>{players.map((p,i)=><div key={p.id} className="flex items-center justify-between border-b py-5 text-xl"><span className="font-bold">{i+1}. {p.nickname}</span><b>{p.score.toFixed(0)} pts</b></div>)}</CardContent></Card>}
 <Card><CardHeader><CardTitle>Players · {players.length}</CardTitle></CardHeader><CardContent>{players.length?players.map(p=><div key={p.id} className="flex justify-between py-2"><span>{p.nickname}</span><span>{p.score}</span></div>):<p className="text-muted-foreground">Waiting for players...</p>}</CardContent></Card></div></main>}

 return <main className="mx-auto max-w-6xl space-y-6 px-6 py-8"><div><p className="text-sm font-semibold text-primary">🟢 LIVE QUIZ</p><h1 className="text-3xl font-bold">Quiz Maker & Selector</h1><p className="text-muted-foreground">Create reusable quizzes, save them, then launch any quiz as a live screen-shared game.</p></div>{error&&<p className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}
 <div className="grid gap-6 lg:grid-cols-[1fr_2fr]"><Card><CardHeader><CardTitle>Saved quizzes</CardTitle></CardHeader><CardContent className="space-y-2">{templates.length?templates.map(t=><button key={t.id} onClick={()=>openTemplate(t)} className={`w-full rounded-lg border p-4 text-left hover:bg-accent ${selected?.id===t.id?'border-primary bg-accent':''}`}><b>{t.title}</b><p className="text-xs text-muted-foreground">Class {t.class_code}</p></button>):<p className="text-sm text-muted-foreground">No saved quizzes yet.</p>}<Button className="mt-2 w-full gap-2" variant="outline" onClick={()=>{setSelected(null);setQuestions([]);setTitle('My Live Quiz');setClassCode('');}}><Plus className="size-4"/>Create New Quiz</Button></CardContent></Card>
 <div className="space-y-6">{!selected?<Card><CardHeader><CardTitle>Create quiz template</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Quiz title"/><Input value={classCode} onChange={e=>setClassCode(e.target.value)} placeholder="Class code"/><Button onClick={createTemplate} disabled={loading}>Save Quiz Template</Button></CardContent></Card>:<Card><CardHeader><CardTitle>{selected.title}</CardTitle><p className="text-sm text-muted-foreground">Class {selected.class_code} · Every question is exactly 30 seconds.</p></CardHeader><CardContent className="space-y-4"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Question"/><div className="grid gap-2 md:grid-cols-2"><Input value={a} onChange={e=>setA(e.target.value)} placeholder="Answer A"/><Input value={b} onChange={e=>setB(e.target.value)} placeholder="Answer B"/><Input value={c} onChange={e=>setC(e.target.value)} placeholder="Answer C"/><Input value={d} onChange={e=>setD(e.target.value)} placeholder="Answer D"/></div><select className="rounded border bg-background px-3 py-2" value={correct} onChange={e=>setCorrect(e.target.value)}><option value="A">A is correct</option><option value="B">B is correct</option><option value="C">C is correct</option><option value="D">D is correct</option></select><Button onClick={add}>Add Question</Button><div className="space-y-2">{questions.map((x,i)=><div key={x.id} className="rounded border p-3"><b>{i+1}.</b> {x.question}<span className="ml-2 text-xs text-muted-foreground">30s · correct {x.correct_answer}</span></div>)}</div><Button className="w-full" disabled={!questions.length||loading} onClick={launchTemplate}><Play className="mr-2 size-4"/>Start This Quiz Live</Button></CardContent></Card>}</div></div></main>;
}
