'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Navbar } from '@/components/Navbar';
import { useLanguage } from '@/components/language-provider';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PlusCircle, BookOpen, Trash2, X, Loader2, Radio, ArrowRight, School, Copy, Check, Sparkles } from 'lucide-react';

type TeacherClass={id?:string;class_name:string;school_name:string;code:string;teacher_id:string};
type CurrentUser={id?:string|number;fullName?:string;full_name?:string;email?:string;role?:string};

export default function TeacherDashboardPage(){
 const {t}=useLanguage();
 const [isModalOpen,setIsModalOpen]=useState(false);const [className,setClassName]=useState('');const [schoolName,setSchoolName]=useState('');const [teacherClasses,setTeacherClasses]=useState<TeacherClass[]>([]);const [currentUserId,setCurrentUserId]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [deletingCode,setDeletingCode]=useState<string|null>(null);const [copiedCode,setCopiedCode]=useState<string|null>(null);
 const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;const supabaseAnonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
 useEffect(()=>{if(typeof window==='undefined')return;try{const rawUser=localStorage.getItem('current_user');if(!rawUser){setCurrentUserId(null);setLoading(false);return;}const parsedUser:CurrentUser=JSON.parse(rawUser);if(parsedUser?.id!==undefined&&parsedUser?.id!==null&&String(parsedUser.id).trim()!==''){setCurrentUserId(String(parsedUser.id).trim());}else{localStorage.removeItem('current_user');setCurrentUserId(null);setLoading(false);}}catch{localStorage.removeItem('current_user');setCurrentUserId(null);setLoading(false);}},[]);
 useEffect(()=>{if(!currentUserId)return;if(!supabaseUrl||!supabaseAnonKey){setLoading(false);return;}async function fetchTeacherClasses(){setLoading(true);try{const response=await fetch(`${supabaseUrl}/rest/v1/teacher_classes?teacher_id=eq.${encodeURIComponent(currentUserId)}&select=*`,{headers:{apikey:supabaseAnonKey,Authorization:`Bearer ${supabaseAnonKey}`,'Content-Type':'application/json'},cache:'no-store'});if(!response.ok)throw new Error(await response.text());const data:TeacherClass[]=await response.json();setTeacherClasses(data.filter(item=>String(item.teacher_id)===String(currentUserId)));}catch(error){console.error('[Teacher Dashboard] Error fetching classes:',error);setTeacherClasses([]);}finally{setLoading(false);}}fetchTeacherClasses();},[currentUserId,supabaseUrl,supabaseAnonKey]);
 const handleCreateClass=async(e:React.FormEvent)=>{e.preventDefault();if(!currentUserId||!supabaseUrl||!supabaseAnonKey||!className.trim()||!schoolName.trim())return;setSubmitting(true);const randomCode=Math.random().toString(36).substring(2,7).toUpperCase();const newClassData={class_name:className.trim(),school_name:schoolName.trim(),code:randomCode,teacher_id:currentUserId};try{const response=await fetch(`${supabaseUrl}/rest/v1/teacher_classes`,{method:'POST',headers:{apikey:supabaseAnonKey,Authorization:`Bearer ${supabaseAnonKey}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(newClassData)});if(!response.ok)throw new Error(await response.text());const createdClasses:TeacherClass[]=await response.json();const createdClass=createdClasses?.[0];if(!createdClass)throw new Error('No class was returned by Supabase.');if(String(createdClass.teacher_id)===String(currentUserId))setTeacherClasses(previous=>[...previous,createdClass]);setClassName('');setSchoolName('');setIsModalOpen(false);}catch(error){console.error('[Teacher Dashboard] Error creating class:',error);}finally{setSubmitting(false);}};
 const handleDeleteClass=async(code:string,e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();if(!currentUserId||!supabaseUrl||!supabaseAnonKey)return;setDeletingCode(code);try{const response=await fetch(`${supabaseUrl}/rest/v1/teacher_classes?code=eq.${encodeURIComponent(code)}&teacher_id=eq.${encodeURIComponent(currentUserId)}`,{method:'DELETE',headers:{apikey:supabaseAnonKey,Authorization:`Bearer ${supabaseAnonKey}`,Prefer:'return=minimal'}});if(!response.ok)throw new Error(await response.text());setTeacherClasses(previous=>previous.filter(item=>!(item.code===code&&String(item.teacher_id)===String(currentUserId))));}catch(error){console.error('[Teacher Dashboard] Error deleting class:',error);}finally{setDeletingCode(null);}};
 const copyCode=async(code:string)=>{try{await navigator.clipboard.writeText(code);setCopiedCode(code);window.setTimeout(()=>setCopiedCode(null),1500);}catch{}};
 const userName=typeof window!=='undefined'?(()=>{try{const u=JSON.parse(localStorage.getItem('current_user')||'{}');return u.fullName||u.full_name||'Teacher';}catch{return'Teacher';}})():'Teacher';
 return <div className="min-h-screen bg-background"><Navbar/><main className="edu-page space-y-8">
  <section className="relative overflow-hidden rounded-3xl border border-border/80 bg-card p-6 shadow-sm sm:p-8">
   <div className="absolute -right-20 -top-24 size-64 rounded-full bg-primary/10 blur-3xl"/><div className="absolute -bottom-24 left-1/3 size-48 rounded-full bg-accent/40 blur-3xl"/>
   <div className="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"><Sparkles className="size-3.5"/>Teacher workspace</div><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">{t('teacherDashboard')}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">{t('teacherDashboardDescription')}</p><p className="mt-3 text-sm font-medium text-foreground">Welcome back, {userName}.</p></div><div className="flex flex-wrap gap-3"><Link href="/dashboard/teacher/live-quiz"><Button size="lg" variant="outline" className="edu-interactive gap-2 rounded-xl"><Radio className="size-4"/>Live Quiz<ArrowRight className="size-4"/></Button></Link><Button size="lg" onClick={()=>setIsModalOpen(true)} disabled={!currentUserId} className="edu-interactive gap-2 rounded-xl shadow-sm"><PlusCircle className="size-5"/>{t('createNewClass')}</Button></div></div>
  </section>
  <section className="grid gap-4 sm:grid-cols-3"><div className="edu-card p-5"><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><School className="size-5"/></div><p className="text-sm font-medium text-muted-foreground">Your classes</p><p className="mt-1 text-3xl font-bold">{loading?'—':teacherClasses.length}</p></div><div className="edu-card p-5"><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-accent text-accent-foreground"><BookOpen className="size-5"/></div><p className="text-sm font-medium text-muted-foreground">Teaching workspace</p><p className="mt-1 text-3xl font-bold">{loading?'—':teacherClasses.length>0?'Ready':'Empty'}</p></div><div className="edu-card p-5"><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Radio className="size-5"/></div><p className="text-sm font-medium text-muted-foreground">Live quizzes</p><p className="mt-1 text-3xl font-bold">Ready</p></div></section>
  <Card className="edu-card overflow-hidden"><CardHeader className="border-b border-border/70 bg-muted/30 px-5 py-5 sm:px-6"><div className="flex items-center justify-between gap-4"><div><CardTitle className="flex items-center gap-2 text-xl"><BookOpen className="size-5 text-primary"/>{t('yourClassesJoinCodes')}</CardTitle><p className="mt-1 text-sm text-muted-foreground">Open a class to manage its courses, assignments and tests.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{teacherClasses.length} {teacherClasses.length===1?'class':'classes'}</span></div></CardHeader><CardContent className="p-4 sm:p-6">
   {loading?<div className="grid gap-3 sm:grid-cols-2"><div className="h-28 animate-pulse rounded-2xl bg-muted"/><div className="h-28 animate-pulse rounded-2xl bg-muted"/></div>:!currentUserId?<div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-6"><p className="font-semibold">Unable to identify the current teacher.</p><p className="mt-1 text-sm text-muted-foreground">Please sign out and sign in again.</p></div>:teacherClasses.length===0?<div className="rounded-2xl border border-dashed border-border p-10 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><School className="size-6"/></div><h3 className="mt-4 font-bold">No classes yet</h3><p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">Create your first class to start adding courses, assignments, tests and students.</p><Button className="mt-5 rounded-xl" onClick={()=>setIsModalOpen(true)}><PlusCircle className="mr-2 size-4"/>Create your first class</Button></div>:<div className="grid gap-3 lg:grid-cols-2">{teacherClasses.map((item,index)=><Link key={item.id||`${item.code}-${index}`} href={`/dashboard/student/classes/${item.code}`} className="group"><div className="edu-interactive flex min-h-32 items-center justify-between gap-4 rounded-2xl border border-border/80 bg-card p-5 hover:border-primary/30 hover:bg-primary/[0.025]"><div className="min-w-0"><div className="mb-3 flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><BookOpen className="size-5"/></div><h4 className="truncate text-lg font-bold">{item.class_name}</h4><p className="mt-1 truncate text-sm text-muted-foreground">{item.school_name}</p></div><div className="flex shrink-0 flex-col items-end gap-3"><div className="rounded-xl border border-border bg-muted/40 px-3 py-2 text-right"><span className="block text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Join code</span><span className="font-mono text-lg font-extrabold tracking-widest text-primary">{item.code}</span></div><div className="flex gap-1"><Button type="button" variant="ghost" size="sm" className="rounded-lg" onClick={e=>{e.preventDefault();e.stopPropagation();copyCode(item.code)}}>{copiedCode===item.code?<Check className="size-4 text-primary"/>:<Copy className="size-4"/>}<span className="sr-only">Copy code</span></Button><Button type="button" variant="ghost" size="sm" disabled={deletingCode===item.code} onClick={e=>handleDeleteClass(item.code,e)} className="rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive">{deletingCode===item.code?<Loader2 className="size-4 animate-spin"/>:<Trash2 className="size-4"/>}<span className="sr-only">Delete class</span></Button></div></div></div></Link>)}</div>}
  </CardContent></Card>
 </main>
 {isModalOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)setIsModalOpen(false)}}><div className="w-full max-w-md overflow-hidden rounded-3xl border border-border bg-card shadow-2xl"><div className="border-b border-border/70 bg-muted/30 p-6"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><School className="size-5"/></div><h3 className="text-xl font-bold">{t('createNewClass')}</h3><p className="mt-1 text-sm text-muted-foreground">Set up a class and we'll generate a unique join code.</p></div><Button variant="ghost" size="icon" onClick={()=>setIsModalOpen(false)} className="rounded-xl"><X className="size-5"/></Button></div></div><form onSubmit={handleCreateClass} className="space-y-5 p-6"><div className="space-y-2"><label className="text-sm font-semibold">{t('className')}</label><Input type="text" placeholder={t('classNamePlaceholder')} value={className} onChange={e=>setClassName(e.target.value)} required className="h-12 rounded-xl bg-background"/></div><div className="space-y-2"><label className="text-sm font-semibold">{t('schoolName')}</label><Input type="text" placeholder={t('schoolNamePlaceholder')} value={schoolName} onChange={e=>setSchoolName(e.target.value)} required className="h-12 rounded-xl bg-background"/></div><div className="flex gap-3 pt-2"><Button type="button" variant="outline" onClick={()=>setIsModalOpen(false)} className="h-11 flex-1 rounded-xl">{t('cancel')}</Button><Button type="submit" disabled={submitting||!currentUserId} className="h-11 flex-1 rounded-xl">{submitting?<Loader2 className="size-4 animate-spin"/>:<><PlusCircle className="mr-2 size-4"/>{t('generateCode')}</>}</Button></div></form></div></div>}
 </div>;
}
