'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileText, Loader2, Lock, Menu, Save, AlertTriangle, X } from 'lucide-react';

type Test={id:string;class_code?:string;course_id?:string;title:string;description?:string|null;published?:boolean;due_date?:string|null;test_password?:string|null;time_limit_minutes?:number|null;max_attempts?:number|null;allow_review?:boolean|null};
type Question={id:string;test_id:string;question_order:number;question:string;question_type?:string|null;option_a?:string|null;option_b?:string|null;option_c?:string|null;option_d?:string|null;correct_answer?:string|null;points?:number|null;answer_data?:Record<string,unknown>|null};
type Submission={id:string;test_id:string;student_id:string;answers:Record<string,string>|null;score:number};
type Attempt={id:string;test_id:string;student_id:string;status?:string|null;answers?:Record<string,string>|null;started_at?:string|null;updated_at?:string|null;completed_at?:string|null};
type Pair={left:string;right:string};
type QType='multiple-choice'|'true-false'|'fill-blank'|'matching';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||'';const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
function getHeaders(json=false){try{const token=localStorage.getItem('supabase_access_token')||key;return {apikey:key,Authorization:`Bearer ${token}`,...(json?{'Content-Type':'application/json'}:{})}}catch{return {apikey:key,Authorization:`Bearer ${key}`,...(json?{'Content-Type':'application/json'}:{})}}}
function studentId(){try{const u=JSON.parse(localStorage.getItem('current_user')||'{}');return String(u.student_id??u.id??u.user_id??u.uid??u.user?.student_id??u.user?.id??'').trim()||null}catch{return null}}
function typeOf(q:Question):QType{const r=String(q.question_type||'multiple-choice').trim().toLowerCase().replace(/_/g,'-').replace(/\s+/g,'-');if(['true-false','truefalse','boolean'].includes(r))return'true-false';if(['fill-blank','fill-in-blank','fill-in-the-blank','fillintheblank','fill-blank-question'].includes(r))return'fill-blank';if(['matching','match'].includes(r))return'matching';return'multiple-choice'}
function pairs(q:Question):Pair[]{try{const p=JSON.parse(String(q.option_a||'[]'));if(Array.isArray(p))return p.map((x:any)=>({left:String(x?.left??''),right:String(x?.right??'')})).filter((x:Pair)=>x.left&&x.right)}catch{}return q.option_a&&q.option_b?[{left:String(q.option_a),right:String(q.option_b)}]:[]}
function norm(v:unknown){return String(v??'').trim().replace(/\s+/g,' ').toLowerCase()}
function tf(v:unknown){const x=norm(v);return x==='a'||x==='true'?'A':x==='b'||x==='false'?'B':x}
function parseMatching(v:string){try{const x=JSON.parse(v||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x as Record<string,string>:{} }catch{return{}}}
function fillAnswer(q:Question){return String(q.option_a??'').trim()||String(q.correct_answer??'').trim()}
function imageOf(q:Question){const a=q.answer_data;return a&&typeof a==='object'&&typeof a.image_url==='string'?a.image_url:''}
function isCorrect(q:Question,a:Record<string,string>){const v=a[q.id]||'',t=typeOf(q);if(t==='fill-blank')return fillAnswer(q).split(/\s*(?:\|\||;|,)\s*/).map(norm).filter(Boolean).includes(norm(v));if(t==='matching'){const s=parseMatching(v),p=pairs(q);return p.length>0&&p.every(x=>norm(s[x.left])===norm(x.right))}if(t==='true-false')return tf(v)===tf(q.correct_answer);return norm(v)===norm(q.correct_answer)}
function answered(q:Question,a:Record<string,string>){if(typeOf(q)==='matching'){const s=parseMatching(a[q.id]||''),p=pairs(q);return p.length>0&&p.every(x=>!!s[x.left])}return Boolean(String(a[q.id]??'').trim())}
function desc(v?:string|null){return(v||'').replace(/^\[\[EQ_PASSWORD:[^\]]+\]\]\s*/,'')}

export default function TakeTestPage(){
 const {id:raw}=useParams<{id:string}>();const id=String(raw||'');const router=useRouter();const sp=useSearchParams();const reviewLatest=sp.get('review')==='latest';
 const[test,setTest]=useState<Test|null>(null),[questions,setQuestions]=useState<Question[]>([]),[answers,setAnswers]=useState<Record<string,string>>({}),[subs,setSubs]=useState<Submission[]>([]),[reviewing,setReviewing]=useState<Submission|null>(null),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[password,setPassword]=useState(''),[entered,setEntered]=useState(''),[unlocked,setUnlocked]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[started,setStarted]=useState<number|null>(null),[remaining,setRemaining]=useState<number|null>(null),[sid,setSid]=useState<string|null>(null),[complete,setComplete]=useState(false),[current,setCurrent]=useState(0),[showNavigator,setShowNavigator]=useState(false),[saveState,setSaveState]=useState<'saved'|'saving'|'error'>('saved');
 const attemptRef=useRef<Attempt|null>(null),answersRef=useRef<Record<string,string>>({}),savingRef=useRef(false),submittingRef=useRef(false),autoRef=useRef(false),deadlineRef=useRef<number|null>(null);
 useEffect(()=>{answersRef.current=answers},[answers]);
 const max=Math.max(1,Number(test?.max_attempts)||1),used=subs.length,left=Math.max(0,max-used),answeredCount=questions.filter(q=>answered(q,answers)).length,progress=questions.length?Math.round(answeredCount/questions.length*100):0;
 const save=useCallback(async(a=answersRef.current)=>{const at=attemptRef.current;if(!at?.id||savingRef.current)return;savingRef.current=true;setSaveState('saving');try{const r=await fetch(`${url}/rest/v1/test_attempts?id=eq.${encodeURIComponent(at.id)}`,{method:'PATCH',headers:{...getHeaders(true),Prefer:'return=minimal'},body:JSON.stringify({answers:a,status:'in_progress',updated_at:new Date().toISOString()})});if(!r.ok)throw new Error();setSaveState('saved')}catch{setSaveState('error')}finally{savingRef.current=false}},[]);
 const finish=useCallback(async(a:Record<string,string>)=>{const at=attemptRef.current;if(!at?.id)return;const now=new Date().toISOString();await fetch(`${url}/rest/v1/test_attempts?id=eq.${encodeURIComponent(at.id)}`,{method:'PATCH',headers:{...getHeaders(true),Prefer:'return=minimal'},body:JSON.stringify({answers:a,status:'completed',updated_at:now,completed_at:now})});attemptRef.current=null},[]);
 const findAttempt=useCallback(async(s:string)=>{const r=await fetch(`${url}/rest/v1/test_attempts?test_id=eq.${encodeURIComponent(id)}&student_id=eq.${encodeURIComponent(s)}&status=eq.in_progress&select=*&order=started_at.desc&limit=1`,{headers:getHeaders(),cache:'no-store'});if(!r.ok)return null;const d=await r.json();if(!Array.isArray(d)||!d[0])return null;const a=d[0] as Attempt;attemptRef.current=a;if(a.answers){answersRef.current=a.answers;setAnswers(a.answers)}return a},[id]);
 const createAttempt=useCallback(async(s:string)=>{const now=new Date().toISOString();const r=await fetch(`${url}/rest/v1/test_attempts`,{method:'POST',headers:{...getHeaders(true),Prefer:'return=representation'},body:JSON.stringify({test_id:id,student_id:s,status:'in_progress',answers:{},started_at:now,updated_at:now})});if(!r.ok)throw new Error(`Could not start test: ${await r.text()}`);const d=await r.json(),a=(Array.isArray(d)?d[0]:d) as Attempt;if(!a?.id)throw new Error('Could not create test attempt.');attemptRef.current=a;return a},[id]);
 const submit=useCallback(async(auto=false)=>{if(!test||!sid||submittingRef.current||reviewing||left<=0)return;if(auto&&autoRef.current)return;if(!auto){if(questions.some(q=>!answered(q,answersRef.current))){setError('Please answer every question before submitting.');setConfirm(false);return}if(!confirm){setConfirm(true);return}}autoRef.current=auto;submittingRef.current=true;setSubmitting(true);setError('');try{const a={...answersRef.current},correct=questions.reduce((n,q)=>n+(isCorrect(q,a)?1:0),0),score=questions.length?Math.round(correct/questions.length*10000)/100:0;const r=await fetch(`${url}/rest/v1/test_submissions`,{method:'POST',headers:{...getHeaders(true),Prefer:'return=representation'},body:JSON.stringify({test_id:id,student_id:sid,answers:a,score})});if(!r.ok)throw new Error(`Submission failed: ${await r.text()}`);const d=await r.json(),row=(Array.isArray(d)?d[0]:d) as Submission;if(!row?.id)throw new Error('Submission was not saved.');await finish(a);try{sessionStorage.removeItem(`student-dashboard:${sid}`)}catch{}setSubs(x=>[{...row,answers:a,score},...x]);setStarted(null);setRemaining(null);deadlineRef.current=null;setAnswers({});answersRef.current={};setConfirm(false);setComplete(true)}catch(e){autoRef.current=false;setError(e instanceof Error?e.message:'Failed to submit test.')}finally{submittingRef.current=false;setSubmitting(false)}},[test,sid,reviewing,left,questions,confirm,id,finish]);
 useEffect(()=>{if(!id)return;let cancelled=false;(async()=>{try{const s=studentId();if(!s)throw new Error('Student UUID not found. Please sign in again.');setSid(s);const tr=await fetch(`${url}/rest/v1/tests?id=eq.${encodeURIComponent(id)}&select=*`,{headers:getHeaders(),cache:'no-store'});const text=await tr.text();if(!tr.ok)throw new Error(`Could not load test (${tr.status}). ${text}`);let rows:any[]=[];try{rows=JSON.parse(text)}catch{}if(!Array.isArray(rows)||!rows.length)throw new Error('Test not found.');const t=rows.find(x=>String(x.id)===id) as Test||null;if(!t)throw new Error('Test not found.');if(t.published===false)throw new Error('This test is not published yet.');if(cancelled)return;setTest(t);const p=String(t.test_password||'').trim();setPassword(p);setUnlocked(!p);const qr=await fetch(`${url}/rest/v1/test_questions?test_id=eq.${encodeURIComponent(id)}&select=*&order=question_order.asc,id.asc`,{headers:getHeaders(),cache:'no-store'});if(!qr.ok)throw new Error(await qr.text());const qs=await qr.json();setQuestions(Array.isArray(qs)?qs:[]);const sr=await fetch(`${url}/rest/v1/test_submissions?test_id=eq.${encodeURIComponent(id)}&student_id=eq.${encodeURIComponent(s)}&select=*&order=id.desc`,{headers:getHeaders(),cache:'no-store'});const rows2=sr.ok?await sr.json():[];const list:Array<Submission>=Array.isArray(rows2)?rows2:[];setSubs(list);if(reviewLatest&&t.allow_review!==false&&list[0]){setReviewing(list[0]);return}if(list.length>=Math.max(1,Number(t.max_attempts)||1))return;const at=await findAttempt(s);if(cancelled)return;if(at){setUnlocked(true);const st=at.started_at?new Date(at.started_at).getTime():Date.now();setStarted(st);if(t.time_limit_minutes){const dl=st+Number(t.time_limit_minutes)*60000;deadlineRef.current=dl;setRemaining(Math.max(0,Math.ceil((dl-Date.now())/1000)))}}else if(!p){const fresh=await createAttempt(s);if(cancelled)return;const st=fresh.started_at?new Date(fresh.started_at).getTime():Date.now();setStarted(st);setUnlocked(true);if(t.time_limit_minutes){const dl=st+Number(t.time_limit_minutes)*60000;deadlineRef.current=dl;setRemaining(Math.max(0,Math.ceil((dl-Date.now())/1000)))}}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Failed to load test.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[id,reviewLatest,findAttempt,createAttempt]);
 useEffect(()=>{if(!started||reviewing||!attemptRef.current||complete||left<=0)return;const i=window.setInterval(()=>void save(),5000);return()=>window.clearInterval(i)},[started,reviewing,complete,left,save]);
 useEffect(()=>{if(!started||reviewing||!attemptRef.current||complete)return;const f=()=>void save();window.addEventListener('pagehide',f);return()=>window.removeEventListener('pagehide',f)},[started,reviewing,complete,save]);
 useEffect(()=>{if(!started||!test?.time_limit_minutes||reviewing||complete||left<=0)return;const dl=deadlineRef.current??started+Number(test.time_limit_minutes)*60000;deadlineRef.current=dl;const tick=()=>{const s=Math.max(0,Math.ceil((dl-Date.now())/1000));setRemaining(s);if(s<=0&&!submittingRef.current)void submit(true)};tick();const i=window.setInterval(tick,250);return()=>window.clearInterval(i)},[started,test?.time_limit_minutes,reviewing,complete,left,submit]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(reviewing||!started)return;if(e.key==='ArrowRight'||e.key==='Enter'){if((e.target as HTMLElement)?.tagName==='INPUT')return;if(current<questions.length-1){e.preventDefault();setCurrent(v=>Math.min(questions.length-1,v+1))}}if(e.key==='ArrowLeft'&&current>0){e.preventDefault();setCurrent(v=>Math.max(0,v-1))}if(e.key==='Escape')setShowNavigator(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[reviewing,started,current,questions.length]);
 const start=async()=>{if(!sid||left<=0)return;try{setError('');const at=await findAttempt(sid)||await createAttempt(sid),st=at.started_at?new Date(at.started_at).getTime():Date.now();setStarted(st);setUnlocked(true);autoRef.current=false;if(test?.time_limit_minutes){const dl=st+Number(test.time_limit_minutes)*60000;deadlineRef.current=dl;setRemaining(Math.max(0,Math.ceil((dl-Date.now())/1000)))}}catch(e){setError(e instanceof Error?e.message:'Could not start test.');setUnlocked(false)}};
 const enter=()=>{if(entered===password)void start();else setError('Incorrect assessment password.')};
 const retry=async()=>{if(left<=0){setError('You have used all available attempts.');return}setError('');setReviewing(null);setCurrent(0);setAnswers({});answersRef.current={};setConfirm(false);setComplete(false);attemptRef.current=null;deadlineRef.current=null;autoRef.current=false;if(password){setEntered('');setUnlocked(false);return}await start()};
 const setAnswer=(qid:string,v:string)=>{const next={...answersRef.current,[qid]:v};answersRef.current=next;setAnswers(next);void save(next)};
 const matchingOptions=useMemo(()=>Array.from(new Set(questions.filter(q=>typeOf(q)==='matching').flatMap(q=>pairs(q).map(p=>p.right)))),[questions]);
 if(loading)return <div className="min-h-screen bg-slate-50 flex items-center justify-center"><div className="text-center"><Loader2 className="mx-auto size-8 animate-spin text-blue-600"/><p className="mt-3 text-sm text-slate-500">Loading assessment…</p></div></div>;
 if(!test)return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><Card className="w-full max-w-md"><CardContent className="p-8 text-center"><p className="text-destructive">{error||'Unable to load test.'}</p><Button className="mt-5" onClick={()=>router.push('/dashboard/student')}>Back to Dashboard</Button></CardContent></Card></main>;
 if(!unlocked&&left>0)return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><Card className="w-full max-w-md overflow-hidden"><div className="h-2 bg-blue-600"/><CardHeader className="p-8 pb-6 text-center"><div className="mx-auto mb-5 flex size-14 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><Lock className="size-6"/></div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Assessment Access</p><CardTitle className="mt-3 text-2xl leading-tight">{test.title}</CardTitle><p className="mt-3 text-sm leading-6 text-slate-500">Enter the assessment password to begin. Your progress will be saved automatically.</p></CardHeader><CardContent className="space-y-6 p-8 pt-2"><div><label htmlFor="assessment-password" className="text-sm font-semibold">Assessment password</label><Input id="assessment-password" autoFocus className="mt-3 h-12" type="password" value={entered} onChange={e=>setEntered(e.target.value)} onKeyDown={e=>e.key==='Enter'&&enter()} /></div>{error&&<p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="grid grid-cols-2 gap-4"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Attempt</p><p className="mt-1 font-bold">{used+1} of {max}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Questions</p><p className="mt-1 font-bold">{questions.length}</p></div></div><div className="space-y-3"><Button className="h-12 w-full bg-blue-600 hover:bg-blue-700" onClick={enter}>Begin Assessment <ChevronRight className="ml-1 size-4"/></Button><Button variant="ghost" className="h-10 w-full" onClick={()=>router.push('/dashboard/student')}>Cancel</Button></div></CardContent></Card></main>;
 if(reviewing)return <main className="min-h-screen bg-slate-50 py-8"><div className="mx-auto max-w-4xl px-5"><div className="mb-7 flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Assessment Review</p><h1 className="mt-1 text-2xl font-bold">{test.title}</h1><p className="mt-1 text-slate-600">Final score <strong>{Number(reviewing.score).toFixed(2)}/100</strong></p></div><Button variant="outline" onClick={()=>setReviewing(null)}>Back</Button></div><div className="space-y-4">{questions.map((q,i)=>{const ok=isCorrect(q,reviewing.answers||{}),a=(reviewing.answers||{})[q.id]||'';return <Card key={q.id} className={`border ${ok?'border-emerald-200':'border-rose-200'}`}><CardHeader><div className="flex justify-between"><CardTitle className="text-base">Question {i+1}</CardTitle><span className={ok?'text-emerald-700':'text-rose-700'}>{ok?'Correct':'Incorrect'}</span></div><p>{q.question}</p></CardHeader><CardContent><p className="text-xs font-semibold uppercase text-slate-500">Your answer</p><p className="mt-1 rounded-lg bg-blue-50 p-3">{typeOf(q)==='matching'?Object.entries(parseMatching(a)).map(([k,v])=>`${k} → ${v}`).join(' • '):a||'No answer'}</p>{!ok&&<><p className="mt-4 text-xs font-semibold uppercase text-emerald-700">Correct answer</p><p className="mt-1 rounded-lg bg-emerald-50 p-3">{typeOf(q)==='fill-blank'?fillAnswer(q):typeOf(q)==='true-false'?(tf(q.correct_answer)==='A'?'True':'False'):typeOf(q)==='matching'?pairs(q).map(p=>`${p.left} → ${p.right}`).join(' • '):(q.correct_answer||'')}</p></>}</CardContent></Card>})}</div></div></main>;
 if(!started||left<=0||complete)return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><Card className="w-full max-w-xl overflow-hidden"><div className="h-2 bg-emerald-500"/><CardContent className="p-10 text-center"><div className="mx-auto mb-4 flex size-14 items-center justify-center rounded-full bg-emerald-500 text-white"><CheckCircle2 className="size-7"/></div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Assessment Complete</p><h2 className="mt-2 text-2xl font-bold">{test.title}</h2><p className="mt-2 text-slate-500">Your latest score</p><p className="mt-1 text-5xl font-bold">{Number(subs[0]?.score||0).toFixed(2)}<span className="text-xl text-slate-400">/100</span></p><p className="mt-3 text-sm text-slate-500">Attempts used: {used}/{max}</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row">{test.allow_review!==false&&subs[0]&&<Button variant="outline" onClick={()=>setReviewing(subs[0])}>Review Assessment</Button>}{left>0&&<Button className="bg-blue-600 hover:bg-blue-700" onClick={()=>void retry()}>Retry Assessment</Button>}<Button variant="outline" onClick={()=>router.push('/dashboard/student')}>Back to Dashboard</Button></div></CardContent></Card></main>;
 const q=questions[current];if(!q)return <main className="min-h-screen bg-slate-50 flex items-center justify-center"><Card><CardContent className="p-8">This test has no questions.</CardContent></Card></main>;
 const qt=typeOf(q),qa=answers[q.id]||'',selected=parseMatching(qa),letters=['A','B','C','D'] as const,time=remaining===null?null:`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;
 const urgent=remaining!==null&&remaining<=60;
 return <div className="min-h-screen bg-slate-50 pb-28 text-slate-900">
  <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 shadow-sm backdrop-blur">
   <div className="mx-auto max-w-5xl px-3 sm:px-6">
    <div className="flex min-h-16 items-center gap-3">
     <div className="flex min-w-0 flex-1 items-center gap-3"><div className="hidden size-9 shrink-0 items-center justify-center rounded-xl bg-blue-600 text-white sm:flex"><FileText className="size-4"/></div><div className="min-w-0"><p className="truncate text-sm font-bold">{test.title}</p><p className="text-xs text-slate-500">Attempt {used+1} of {max} · {answeredCount}/{questions.length} answered</p></div></div>
     <div className="flex items-center gap-2"><div className={`hidden items-center gap-1.5 text-xs font-medium sm:flex ${saveState==='error'?'text-rose-600':'text-slate-500'}`}>{saveState==='saving'?<><Loader2 className="size-3 animate-spin"/>Saving…</>:saveState==='error'?<><AlertTriangle className="size-3"/>Not saved</>:<><Save className="size-3"/>Saved</>}</div>{time!==null&&<div className={`flex items-center gap-2 rounded-xl border px-3 py-2 font-mono text-sm font-bold ${urgent?'border-rose-200 bg-rose-50 text-rose-700':'border-blue-200 bg-blue-50 text-blue-700'}`}><Clock3 className="size-4"/>{time}</div>}<Button variant="outline" size="icon" className="size-9 sm:hidden" onClick={()=>setShowNavigator(true)} aria-label="Open question navigator"><Menu className="size-4"/></Button></div>
    </div>
    <div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600 transition-all duration-300" style={{width:`${progress}%`}}/></div>
   </div>
  </header>
  <main className="mx-auto max-w-5xl px-3 py-5 sm:px-6 sm:py-8">
   <div className="grid gap-5 lg:grid-cols-[1fr_250px]">
    <div>
     <div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Question {current+1}</p><p className="mt-1 text-sm text-slate-500">{questions.length-current-1} remaining</p></div><div className="text-right"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{qt==='fill-blank'?'Fill in the blank':qt==='true-false'?'True / False':qt==='matching'?'Matching':'Multiple choice'}</span></div></div>
     <Card className="overflow-hidden border-slate-200 shadow-sm">
      <CardHeader className="border-b border-slate-100 bg-white p-5 sm:p-7"><div className="flex items-start gap-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-blue-600 text-sm font-bold text-white shadow-sm">{current+1}</div><div className="min-w-0 flex-1"><CardTitle className="text-lg leading-7 sm:text-xl sm:leading-8">{q.question}</CardTitle>{imageOf(q)&&<img src={imageOf(q)} alt="Question" className="mt-5 max-h-80 w-full rounded-xl border border-slate-200 object-contain bg-slate-50"/>}</div></div></CardHeader>
      <CardContent className="p-4 sm:p-7">
       {qt==='multiple-choice'&&<div className="grid gap-3">{letters.map(l=>{const text=q[`option_${l.toLowerCase()}` as 'option_a'|'option_b'|'option_c'|'option_d'];if(!text)return null;const sel=qa===l;return <button key={l} type="button" onClick={()=>setAnswer(q.id,l)} className={`group flex min-h-16 items-center gap-4 rounded-2xl border-2 p-4 text-left transition-all ${sel?'border-blue-600 bg-blue-50 shadow-sm':'border-slate-200 bg-white hover:border-blue-300 hover:bg-slate-50'}`}><span className={`flex size-9 shrink-0 items-center justify-center rounded-full border-2 text-sm font-bold transition-colors ${sel?'border-blue-600 bg-blue-600 text-white':'border-slate-300 bg-white text-slate-600 group-hover:border-blue-400'}`}>{l}</span><span className="flex-1 text-sm leading-6 sm:text-base">{text}</span>{sel&&<Check className="size-5 shrink-0 text-blue-600"/>}</button>})}</div>}
       {qt==='true-false'&&<div className="grid gap-3 sm:grid-cols-2">{[['A','True'],['B','False']].map(([l,label])=>{const sel=tf(qa)===l;return <button key={l} type="button" onClick={()=>setAnswer(q.id,l)} className={`flex min-h-20 items-center justify-center gap-3 rounded-2xl border-2 p-5 text-lg font-semibold transition-all ${sel?'border-blue-600 bg-blue-600 text-white shadow-sm':'border-slate-200 bg-white hover:border-blue-300 hover:bg-slate-50'}`}>{sel&&<Check className="size-5"/>}{label}</button>})}</div>}
       {qt==='fill-blank'&&<div><label className="text-sm font-semibold text-slate-700">Your answer</label><Input autoComplete="off" autoFocus className="mt-3 h-14 border-2 border-slate-200 text-base focus:border-blue-500" value={qa} onChange={e=>setAnswer(q.id,e.target.value)} placeholder="Type your answer here"/><p className="mt-2 flex items-center gap-1.5 text-xs text-slate-500"><Save className="size-3"/>Saved automatically as you type.</p></div>}
       {qt==='matching'&&<div className="space-y-3">{pairs(q).map(p=><div key={p.left} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="grid gap-2 sm:grid-cols-[1fr_28px_1fr] sm:items-center"><div className="rounded-xl bg-white p-3 text-sm font-medium shadow-sm">{p.left}</div><div className="hidden text-center text-slate-400 sm:block">→</div><select aria-label={`Match for ${p.left}`} className="h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm" value={selected[p.left]||''} onChange={e=>setAnswer(q.id,JSON.stringify({...selected,[p.left]:e.target.value}))}><option value="">Select a match</option>{matchingOptions.map(o=><option key={o} value={o}>{o}</option>)}</select></div></div>)}</div>}
      </CardContent>
     </Card>
     {error&&<div className="mt-4 flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><AlertTriangle className="mt-0.5 size-4 shrink-0"/><span>{error}</span></div>}
     {confirm&&<Card className="mt-5 border-amber-200 bg-amber-50/50"><CardContent className="p-4 sm:p-5"><div className="flex items-start gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-amber-100 text-amber-700"><AlertTriangle className="size-4"/></div><div className="min-w-0 flex-1"><p className="font-semibold">Ready to submit?</p><p className="mt-1 text-sm text-slate-600">You have answered <strong>{answeredCount} of {questions.length}</strong> questions. You will use one attempt and cannot edit these answers afterward.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:justify-end"><Button variant="outline" onClick={()=>setConfirm(false)}>Continue answering</Button><Button className="bg-blue-600 hover:bg-blue-700" onClick={()=>void submit(false)} disabled={submitting}>{submitting?'Submitting…':'Confirm Assessment'}</Button></div></div></div></CardContent></Card>}
    </div>
    <aside className="hidden lg:block"><Card className="sticky top-24 border-slate-200 shadow-sm"><CardHeader className="pb-3"><div className="flex items-center justify-between"><CardTitle className="text-sm">Questions</CardTitle><span className="text-xs text-slate-500">{answeredCount}/{questions.length}</span></div></CardHeader><CardContent className="pt-0"><div className="grid grid-cols-5 gap-2">{questions.map((question,i)=>{const done=answered(question,answers);return <button key={question.id} type="button" onClick={()=>setCurrent(i)} aria-label={`Question ${i+1}${done?' answered':''}`} className={`relative flex size-9 items-center justify-center rounded-lg text-xs font-bold transition-all ${current===i?'bg-blue-600 text-white ring-2 ring-blue-200':done?'bg-emerald-100 text-emerald-700 hover:bg-emerald-200':'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{i+1}{done&&<span className="absolute -right-1 -top-1 flex size-3.5 items-center justify-center rounded-full bg-emerald-500 text-white"><Check className="size-2.5"/></span>}</button>})}</div><div className="mt-4 space-y-2 text-xs text-slate-500"><div className="flex items-center gap-2"><span className="size-3 rounded bg-blue-600"/>Current</div><div className="flex items-center gap-2"><span className="size-3 rounded bg-emerald-100"/>Answered</div><div className="flex items-center gap-2"><span className="size-3 rounded bg-slate-100"/>Unanswered</div></div></CardContent></Card></aside>
   </div>
  </main>
  {showNavigator&&<div className="fixed inset-0 z-50 bg-slate-950/40 lg:hidden" onClick={()=>setShowNavigator(false)}><div className="absolute right-0 top-0 h-full w-[min(340px,88vw)] overflow-y-auto bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><div><p className="font-bold">Question navigator</p><p className="text-xs text-slate-500">{answeredCount} of {questions.length} answered</p></div><Button variant="ghost" size="icon" onClick={()=>setShowNavigator(false)}><X className="size-4"/></Button></div><div className="grid grid-cols-5 gap-2">{questions.map((question,i)=>{const done=answered(question,answers);return <button key={question.id} type="button" onClick={()=>{setCurrent(i);setShowNavigator(false)}} className={`relative flex aspect-square items-center justify-center rounded-xl text-sm font-bold ${current===i?'bg-blue-600 text-white ring-2 ring-blue-200':done?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{i+1}{done&&<Check className="absolute right-1 top-1 size-3 text-emerald-600"/>}</button>})}</div></div></div>}
  <footer className="fixed bottom-0 left-0 right-0 z-40 border-t border-slate-200 bg-white/95 shadow-lg backdrop-blur"><div className="mx-auto flex max-w-5xl items-center gap-2 px-3 py-3 sm:px-6"><Button variant="outline" className="h-11 rounded-xl" onClick={()=>setCurrent(v=>Math.max(0,v-1))} disabled={current===0}><ChevronLeft className="size-4 sm:mr-1"/><span className="hidden sm:inline">Previous</span></Button><Button variant="outline" className="h-11 flex-1 rounded-xl sm:hidden" onClick={()=>setShowNavigator(true)}><Menu className="mr-2 size-4"/>Questions</Button><div className="hidden flex-1 sm:block"><div className="flex items-center justify-center gap-2 text-xs text-slate-500"><span className="font-semibold text-blue-700">{answeredCount}</span> of {questions.length} answered</div></div>{current<questions.length-1?<Button className="h-11 rounded-xl bg-blue-600 px-5 hover:bg-blue-700" onClick={()=>setCurrent(v=>Math.min(questions.length-1,v+1))}>Next<span className="hidden sm:inline"> question</span><ChevronRight className="size-4 sm:ml-1"/></Button>:<Button className="h-11 rounded-xl bg-blue-600 px-5 hover:bg-blue-700" onClick={()=>void submit(false)} disabled={submitting||confirm}>Submit Assessment</Button>}</div></footer>
 </div>;
}
