export const translations = {
  en: {
    // Navbar
    overview: 'Overview', children: 'Children', role: 'Role', guestUser: 'Guest User', exit: 'Exit', english: 'English', indonesian: 'Bahasa Indonesia',
    // Teacher dashboard
    teacherDashboard: 'Teacher Dashboard', teacherDashboardDescription: 'Manage your classes, generate join codes, and review student progress.', createNewClass: 'Create New Class', yourClassesJoinCodes: 'Your Classes & Join Codes', noClassesCreated: 'No classes created yet. Click "Create New Class" above to start!', school: 'School', joinCode: 'Join Code', className: 'Class Name', schoolName: 'School Name', cancel: 'Cancel', generateCode: 'Generate Code', classNamePlaceholder: 'e.g., Advanced Mathematics', schoolNamePlaceholder: 'e.g., Lincoln High School',
    // Student dashboard
    studentDashboard: 'Student Dashboard', studentDashboardDescription: 'Track your coursework, join classes with a code, and view upcoming assignments.', classCodeInput: 'Class Code Input', enterCodePlaceholder: 'Enter code (e.g., A3F92)', joinClass: 'Join Class', codeInvalid: 'Code is invalid', alreadyJoined: 'You have already joined this class.', failedToJoin: 'Failed to join', unknownError: 'Unknown error', networkErrorJoining: 'Network error joining class.', classesYouAreIn: 'Classes You Are In', noClassesJoined: "You haven't joined any classes yet. Enter a valid code above!", active: 'Active',
    // Class details
    backToDashboard: 'Back to Dashboard', classCode: 'Class Code', createNewCourse: 'Create new course', courses: 'Courses', teacherAnnouncementsMaterials: 'Teacher Announcements & Materials', noCoursesCreated: 'Teacher announcements, materials, and quizzes for this class will appear here. No courses created yet.', courseMaterialsDescription: 'Course materials, assignments, and lessons for', willAppearHere: 'will appear here.', materials: 'Materials', addMaterial: 'Add material', noMaterials: 'No materials have been added to this course yet.', createNewCourseModal: 'Create New Course', courseName: 'Course Name', courseNamePlaceholder: 'e.g., Mathematics - Module 1', createCourse: 'Create Course', addMaterialModal: 'Add Material', addingTo: 'Adding to', name: 'Name', materialNamePlaceholder: 'e.g., Chapter 1 Notes', link: 'Link', createMaterial: 'Create Material', materialLinkPlaceholder: 'https://example.com/material',
  },
  id: {
    overview: 'Ringkasan', children: 'Anak', role: 'Peran', guestUser: 'Pengguna Tamu', exit: 'Keluar', english: 'English', indonesian: 'Bahasa Indonesia',
    teacherDashboard: 'Dasbor Guru', teacherDashboardDescription: 'Kelola kelas, buat kode bergabung, dan tinjau perkembangan siswa.', createNewClass: 'Buat Kelas Baru', yourClassesJoinCodes: 'Kelas & Kode Bergabung Anda', noClassesCreated: 'Belum ada kelas yang dibuat. Klik "Buat Kelas Baru" di atas untuk memulai!', school: 'Sekolah', joinCode: 'Kode Bergabung', className: 'Nama Kelas', schoolName: 'Nama Sekolah', cancel: 'Batal', generateCode: 'Buat Kode', classNamePlaceholder: 'contoh: Matematika Lanjutan', schoolNamePlaceholder: 'contoh: SMA Labschool',
    studentDashboard: 'Dasbor Siswa', studentDashboardDescription: 'Pantau tugas sekolah, bergabung dengan kelas menggunakan kode, dan lihat tugas yang akan datang.', classCodeInput: 'Masukkan Kode Kelas', enterCodePlaceholder: 'Masukkan kode (contoh: A3F92)', joinClass: 'Gabung Kelas', codeInvalid: 'Kode tidak valid', alreadyJoined: 'Anda sudah bergabung dengan kelas ini.', failedToJoin: 'Gagal bergabung', unknownError: 'Kesalahan tidak diketahui', networkErrorJoining: 'Terjadi kesalahan jaringan saat bergabung dengan kelas.', classesYouAreIn: 'Kelas yang Anda Ikuti', noClassesJoined: 'Anda belum bergabung dengan kelas apa pun. Masukkan kode yang valid di atas!', active: 'Aktif',
    backToDashboard: 'Kembali ke Dasbor', classCode: 'Kode Kelas', createNewCourse: 'Buat mata pelajaran baru', courses: 'Mata Pelajaran', teacherAnnouncementsMaterials: 'Pengumuman & Materi Guru', noCoursesCreated: 'Pengumuman guru, materi, dan kuis untuk kelas ini akan muncul di sini. Belum ada mata pelajaran yang dibuat.', courseMaterialsDescription: 'Materi, tugas, dan pelajaran untuk', willAppearHere: 'akan muncul di sini.', materials: 'Materi', addMaterial: 'Tambah materi', noMaterials: 'Belum ada materi yang ditambahkan ke mata pelajaran ini.', createNewCourseModal: 'Buat Mata Pelajaran Baru', courseName: 'Nama Mata Pelajaran', courseNamePlaceholder: 'contoh: Matematika - Modul 1', createCourse: 'Buat Mata Pelajaran', addMaterialModal: 'Tambah Materi', addingTo: 'Menambahkan ke', name: 'Nama', materialNamePlaceholder: 'contoh: Catatan Bab 1', link: 'Tautan', createMaterial: 'Buat Materi', materialLinkPlaceholder: 'https://example.com/material',
  },
  es: {
    overview: 'Resumen', children: 'Niños', role: 'Rol', guestUser: 'Usuario invitado', exit: 'Salir', english: 'Inglés', indonesian: 'Bahasa Indonesia',
    teacherDashboard: 'Panel del profesor', teacherDashboardDescription: 'Administra tus clases, genera códigos de acceso y revisa el progreso de los estudiantes.', createNewClass: 'Crear nueva clase', yourClassesJoinCodes: 'Tus clases y códigos de acceso', noClassesCreated: 'Aún no se han creado clases. ¡Haz clic en "Crear nueva clase" arriba para comenzar!', school: 'Escuela', joinCode: 'Código de acceso', className: 'Nombre de la clase', schoolName: 'Nombre de la escuela', cancel: 'Cancelar', generateCode: 'Generar código', classNamePlaceholder: 'ej.: Matemáticas avanzadas', schoolNamePlaceholder: 'ej.: Lincoln High School',
    studentDashboard: 'Panel del estudiante', studentDashboardDescription: 'Consulta tus cursos, únete a clases con un código y revisa las próximas tareas.', classCodeInput: 'Código de clase', enterCodePlaceholder: 'Introduce el código (ej.: A3F92)', joinClass: 'Unirse a la clase', codeInvalid: 'El código no es válido', alreadyJoined: 'Ya te has unido a esta clase.', failedToJoin: 'No se pudo unir', unknownError: 'Error desconocido', networkErrorJoining: 'Error de red al unirse a la clase.', classesYouAreIn: 'Tus clases', noClassesJoined: 'Aún no te has unido a ninguna clase. ¡Introduce un código válido arriba!', active: 'Activa',
    backToDashboard: 'Volver al panel', classCode: 'Código de clase', createNewCourse: 'Crear nuevo curso', courses: 'Cursos', teacherAnnouncementsMaterials: 'Anuncios y materiales del profesor', noCoursesCreated: 'Los anuncios, materiales y cuestionarios de esta clase aparecerán aquí. Aún no se han creado cursos.', courseMaterialsDescription: 'Materiales, tareas y lecciones del curso para', willAppearHere: 'aparecerán aquí.', materials: 'Materiales', addMaterial: 'Añadir material', noMaterials: 'Aún no se han añadido materiales a este curso.', createNewCourseModal: 'Crear nuevo curso', courseName: 'Nombre del curso', courseNamePlaceholder: 'ej.: Matemáticas - Módulo 1', createCourse: 'Crear curso', addMaterialModal: 'Añadir material', addingTo: 'Añadiendo a', name: 'Nombre', materialNamePlaceholder: 'ej.: Apuntes del capítulo 1', link: 'Enlace', createMaterial: 'Crear material', materialLinkPlaceholder: 'https://example.com/material',
  },
  hi: {
    overview: 'अवलोकन', children: 'बच्चे', role: 'भूमिका', guestUser: 'अतिथि उपयोगकर्ता', exit: 'बाहर निकलें', english: 'अंग्रेज़ी', indonesian: 'बहासा इंडोनेशिया',
    teacherDashboard: 'शिक्षक डैशबोर्ड', teacherDashboardDescription: 'अपनी कक्षाएँ प्रबंधित करें, शामिल होने के कोड बनाएँ और छात्रों की प्रगति देखें।', createNewClass: 'नई कक्षा बनाएँ', yourClassesJoinCodes: 'आपकी कक्षाएँ और शामिल होने के कोड', noClassesCreated: 'अभी तक कोई कक्षा नहीं बनाई गई है। शुरू करने के लिए ऊपर "नई कक्षा बनाएँ" पर क्लिक करें!', school: 'स्कूल', joinCode: 'जॉइन कोड', className: 'कक्षा का नाम', schoolName: 'स्कूल का नाम', cancel: 'रद्द करें', generateCode: 'कोड बनाएँ', classNamePlaceholder: 'उदा.: उन्नत गणित', schoolNamePlaceholder: 'उदा.: लिंकन हाई स्कूल',
    studentDashboard: 'छात्र डैशबोर्ड', studentDashboardDescription: 'अपने पाठ्यक्रम का प्रबंधन करें, कोड से कक्षाओं में शामिल हों और आने वाले असाइनमेंट देखें।', classCodeInput: 'कक्षा कोड', enterCodePlaceholder: 'कोड दर्ज करें (उदा.: A3F92)', joinClass: 'कक्षा में शामिल हों', codeInvalid: 'कोड अमान्य है', alreadyJoined: 'आप पहले से इस कक्षा में शामिल हैं।', failedToJoin: 'शामिल नहीं हो सके', unknownError: 'अज्ञात त्रुटि', networkErrorJoining: 'कक्षा में शामिल होते समय नेटवर्क त्रुटि हुई।', classesYouAreIn: 'आपकी कक्षाएँ', noClassesJoined: 'आप अभी तक किसी कक्षा में शामिल नहीं हुए हैं। ऊपर एक मान्य कोड दर्ज करें!', active: 'सक्रिय',
    backToDashboard: 'डैशबोर्ड पर वापस जाएँ', classCode: 'कक्षा कोड', createNewCourse: 'नया पाठ्यक्रम बनाएँ', courses: 'पाठ्यक्रम', teacherAnnouncementsMaterials: 'शिक्षक की घोषणाएँ और सामग्री', noCoursesCreated: 'इस कक्षा की शिक्षक घोषणाएँ, सामग्री और क्विज़ यहाँ दिखाई देंगे। अभी तक कोई पाठ्यक्रम नहीं बनाया गया है।', courseMaterialsDescription: 'के लिए पाठ्यक्रम सामग्री, असाइनमेंट और पाठ', willAppearHere: 'यहाँ दिखाई देंगे।', materials: 'सामग्री', addMaterial: 'सामग्री जोड़ें', noMaterials: 'अभी तक इस पाठ्यक्रम में कोई सामग्री नहीं जोड़ी गई है।', createNewCourseModal: 'नया पाठ्यक्रम बनाएँ', courseName: 'पाठ्यक्रम का नाम', courseNamePlaceholder: 'उदा.: गणित - मॉड्यूल 1', createCourse: 'पाठ्यक्रम बनाएँ', addMaterialModal: 'सामग्री जोड़ें', addingTo: 'इसमें जोड़ रहे हैं', name: 'नाम', materialNamePlaceholder: 'उदा.: अध्याय 1 के नोट्स', link: 'लिंक', createMaterial: 'सामग्री बनाएँ', materialLinkPlaceholder: 'https://example.com/material',
  },
  // These languages use Google Translate for the rest of the page. English is the local fallback for UI keys not translated here.
  'zh-CN': {},
  fr: {},
  ar: {},
} as const

export type Language = keyof typeof translations
export type TranslationKey = keyof typeof translations.en
