'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ChevronDown, ChevronUp, Eye, EyeOff, Pencil, PlusCircle, Trash2, FlaskConical, CheckCircle2, Clock3 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Question, Test } from './types';

type Props = { tests: Test[]; questions: Record<string, Question[]>; teacher: boolean; open: Record<string, boolean>; busy?: boolean; displayDate: (value?: string | null) => string; formatPoints: (count: number) => number; questionTypeLabel: (type?: Question['question_type']) => string; onCreate: () => void; onTogglePublish: (test: Test) => void; onEdit: (test: Test) => void; onDelete: (test: Test) => void; onToggleQuestions: (id: string) => void; onEditQuestion: (question: Question) => void; onDeleteQuestion: (question: Question) => void };
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!; const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!; const headers = { apikey: supabaseKey, Authorization: `Bearer ${supabaseKey}` }; type AttemptMap = Record<string, number>;
function getStudentId() { try { const raw=localStorage.getItem('current_user'); if(!raw)return ''; const u=JSON.parse(raw); return String(u.student_id??u.id??u.user_id??u.uid??u.user?.student_id??u.user?.id??'').trim(); } catch{return '';} }
function matchingPairs(value:string){try{const parsed=JSON.parse(value||'[]');if(!Array.isArray(parsed))return [];return parsed.filter((p:any)=>p?.left&&p?.right).map((p:any)=>`${String(p.left)} → ${String(p.right)}`);}catch{return value?[value]:[];}}
export default function TestsSection({tests,questions,teacher,open,busy,displayDate,formatPoints,questionTypeLabel,onCreate,onTogglePublish,onEdit,onDelete,onToggleQuestions,onEditQuestion,onDeleteQuestion}:Props){
 const [studentId,setStudentId]=useState(''); const [attempts,setAttempts]=useState<AttemptMap>({});
 useEffect(()=>{if(!teacher)setStudentId(getStudentId());},[teacher]);
 useEffect(()=>{if(teacher||!studentId||!tests.length){setAttempts({});return;}let cancelled=false;(async()=>{const next:AttemptMap={};await Promise.all(tests.map(async test=>{try{const response=await fetch(`${supabaseUrl}/rest/v1/test_submissions?test_id=eq.${encodeURIComponent(test.id)}&student_id=eq.${encodeURIComponent(studentId)}&select=id`,{headers,cache:'no-store'});if(!response.ok){next[test.id]=0;return;}const rows=await response.json();next[test.id]=Array.isArray(rows)?rows.length:0;}catch{next[test.id]=0;}}));if(!cancelled)setAttempts(next);})();return()=>{cancelled=true;};},[teacher,studentId,tests.map(test=>`${test.id}:${test.max_attempts}`).join('|')]);
 return <section className="space-y-3">
  <div className="flex items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 text-base font-bold tracking-tight"><span className="flex size-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><FlaskConical className="size-4"/></span>Tests</h3><p className="mt-0.5 text-xs text-muted-foreground">{teacher?'Drafts and published tests for this course.':'Published tests for this course.'}</p></div>{teacher&&<Button type="button" size="sm" className="rounded-xl shadow-sm" onClick={onCreate} disabled={busy}><PlusCircle className="mr-1 size-4"/>Test Maker</Button>}</div>
  {tests.length?tests.map(test=>{const qs=questions[test.id]||[];const used=attempts[test.id]||0;const max=Math.max(1,Number(test.max_attempts)||1);const exhausted=!teacher&&used>=max;const target=exhausted&&test.allow_review!==false?`/dashboard/student/tests/${encodeURIComponent(test.id)}/review`:`/dashboard/student/tests/${encodeURIComponent(test.id)}`;return <div key={test.id} className="overflow-hidden rounded-2xl border border-border/70 bg-card shadow-sm transition-all duration-200 hover:shadow-md">
   <div className="flex items-start gap-3 p-4 sm:p-5"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-muted text-muted-foreground"><FlaskConical className="size-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold">{test.title}</h4><span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${test.published?'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400':'bg-muted text-muted-foreground'}`}>{test.published?'Published':'Draft'}</span></div>{test.description&&<p className="mt-1 text-sm leading-5 text-muted-foreground">{test.description}</p>}<div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground"><span>{qs.length} question{qs.length===1?'':'s'}</span>{qs.length>0&&<span>{formatPoints(qs.length)} pts/question</span>}{test.due_date&&<span className="flex items-center gap-1"><Clock3 className="size-3"/>Due {displayDate(test.due_date)}</span>}</div>{!teacher&&test.published&&<div className="mt-3 flex flex-wrap items-center gap-2"> <Link href={target}><Button type="button" size="sm" className="rounded-xl" variant={exhausted?'outline':'default'}>{exhausted?'Review Test':'Take Test'}</Button></Link>{exhausted?<span className="flex items-center gap-1 text-xs font-medium text-muted-foreground"><CheckCircle2 className="size-3.5"/>All {max} attempt{max===1?'':'s'} used</span>:<span className="text-xs text-muted-foreground">Attempt {used+1} of {max}</span>}</div>}</div>
   {teacher&&<div className="flex shrink-0 gap-1"><Button type="button" variant="outline" size="icon" className="size-9 rounded-lg" onClick={()=>onTogglePublish(test)} title={test.published?'Unpublish':'Publish'}>{test.published?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</Button><Button type="button" variant="outline" size="sm" className="rounded-lg" onClick={()=>onEdit(test)}><Pencil className="mr-1 size-4"/>Edit</Button><Button type="button" variant="ghost" size="icon" className="size-9 rounded-lg text-muted-foreground hover:text-destructive" onClick={()=>onDelete(test)}><Trash2 size={14}/></Button><Button type="button" variant="ghost" size="icon" className="size-9 rounded-lg" onClick={()=>onToggleQuestions(test.id)}>{open[test.id]?<ChevronUp/>:<ChevronDown/>}</Button></div>}
   </div>
   {teacher&&open[test.id]&&<div className="space-y-2 border-t border-border/70 bg-muted/10 p-4 sm:p-5">{qs.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-muted-foreground">No questions yet. Open Test Maker to add them.</p>}{qs.map((question,index)=>{const type=question.question_type||'multiple-choice';return <div key={question.id} className="rounded-xl border border-border/70 bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{index+1}. {question.question}</p><span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">{questionTypeLabel(type)}</span></div>{type==='multiple-choice'&&<div className="mt-2 grid gap-1 text-sm text-muted-foreground md:grid-cols-2"><span>A: {question.option_a}</span><span>B: {question.option_b}</span><span>C: {question.option_c}</span><span>D: {question.option_d}</span></div>}{type==='true-false'&&<p className="mt-2 text-sm text-muted-foreground">Students choose True or False.</p>}{type==='fill-blank'&&<p className="mt-2 text-sm text-muted-foreground">Students type the answer. Correct answer: <b>{question.option_a}</b></p>}{type==='matching'&&<div className="mt-2 space-y-1 text-sm text-muted-foreground">{matchingPairs(question.option_a).map((pair:string,i:number)=><div key={i} className="rounded-lg bg-muted/50 px-2 py-1">{pair}</div>)}</div>}<p className="mt-2 text-xs text-muted-foreground">{formatPoints(qs.length)} pts</p></div><div className="flex shrink-0 gap-1"><Button type="button" variant="ghost" size="icon" className="size-8" onClick={()=>onEditQuestion(question)}><Pencil className="size-3"/></Button><Button type="button" variant="ghost" size="icon" className="size-8 text-muted-foreground hover:text-destructive" onClick={()=>onDeleteQuestion(question)}><Trash2 className="size-3"/></Button></div></div></div>})}<Button type="button" variant="outline" size="sm" className="rounded-xl" onClick={()=>onEdit(test)}><Pencil className="mr-1 size-4"/>Open Test Maker</Button></div>}
  </div>}) : <div className="rounded-2xl border border-dashed border-border bg-muted/20 px-5 py-8 text-center"><FlaskConical className="mx-auto size-7 text-muted-foreground/60"/><p className="mt-2 text-sm font-medium">{teacher?'No tests yet':'No published tests yet'}</p><p className="mt-1 text-xs text-muted-foreground">{teacher?'Create your first test with Test Maker.':'Your teacher has not published a test here yet.'}</p></div>}
 </section>;
}
