'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Camera, Check, ChevronDown, Globe, KeyRound, Loader2, LogOut, Mail, Search, Sun, Shield, Trash2, User, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ThemeToggle } from '@/components/theme-toggle';
import { useLanguage } from '@/components/language-provider';
import type { Language } from '@/lib/translations';

type UserData={id?:string;user_id?:string;student_id?:string;uid?:string;fullName?:string;full_name?:string;email?:string;role?:string;country?:string;avatar_url?:string};
const FLAGS:Record<string,string>={en:'us',id:'id','zh-CN':'cn',es:'es',hi:'in',fr:'fr',ar:'sa'};
const flag=(l:string)=>`https://flagcdn.com/24x18/${FLAGS[l]||'us'}.png`;
const countryCodes=['AF','AL','DZ','AD','AO','AG','AR','AM','AU','AT','AZ','BS','BH','BD','BB','BY','BE','BZ','BJ','BT','BO','BA','BW','BR','BN','BG','BF','BI','CV','KH','CM','CA','CF','TD','CL','CN','CO','KM','CG','CR','HR','CU','CY','CZ','DK','DJ','DM','DO','EC','EG','SV','GQ','ER','EE','SZ','ET','FJ','FI','FR','GA','GM','GE','DE','GH','GR','GD','GT','GN','GW','GY','HT','HN','HU','IS','IN','ID','IR','IQ','IE','IT','JM','JP','JO','KZ','KE','KI','KP','KR','XK','KW','KG','LA','LV','LB','LS','LR','LY','LI','LT','LU','MG','MW','MY','MV','ML','MT','MH','MR','MU','MX','FM','MD','MC','MN','ME','MA','MZ','MM','NA','NR','NP','NL','NZ','NI','NE','NG','MK','NO','OM','PK','PW','PS','PA','PG','PY','PE','PH','PL','PT','QA','RO','RU','RW','KN','LC','VC','WS','SM','ST','SA','SN','RS','SC','SL','SG','SK','SI','SB','SO','ZA','SS','ES','LK','SD','SR','SE','CH','SY','TW','TJ','TZ','TH','TL','TG','TO','TT','TN','TR','TM','TV','UG','UA','AE','GB','US','UY','UZ','VU','VA','VE','VN','YE','ZM','ZW'];

export default function SettingsPage(){
 const router=useRouter();const {language,setLanguage,languages}=useLanguage();const fileRef=useRef<HTMLInputElement>(null);const countryDropdownRef=useRef<HTMLDivElement>(null);const countrySearchRef=useRef<HTMLInputElement>(null);
 const [user,setUser]=useState<UserData|null>(null);const [name,setName]=useState('');const [country,setCountry]=useState('');const [avatar,setAvatar]=useState('');const [email,setEmail]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [deleteOpen,setDeleteOpen]=useState(false);const [deleting,setDeleting]=useState(false);const [password,setPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [changingPassword,setChangingPassword]=useState(false);const [isCountryOpen,setIsCountryOpen]=useState(false);const [countrySearch,setCountrySearch]=useState('');
 const countries=useMemo(()=>{const displayNames=new Intl.DisplayNames(['en'],{type:'region'});return countryCodes.map(code=>({code:code.toLowerCase(),name:displayNames.of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name));},[]);
 const filteredCountries=useMemo(()=>{const query=countrySearch.trim().toLowerCase();if(!query)return countries;return countries.filter(c=>c.name.toLowerCase().startsWith(query));},[countries,countrySearch]);
 const selectedCountryObj=countries.find(c=>c.name===country);
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,'')||'';const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
 const authHeaders=useMemo(()=>{let token='';try{token=localStorage.getItem('supabase_access_token')||localStorage.getItem('access_token')||'';}catch{}return{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json'}},[key]);
 useEffect(()=>{function handleClickOutside(event:MouseEvent){if(countryDropdownRef.current&&!countryDropdownRef.current.contains(event.target as Node))setIsCountryOpen(false);}document.addEventListener('mousedown',handleClickOutside);return()=>document.removeEventListener('mousedown',handleClickOutside);},[]);
 useEffect(()=>{if(isCountryOpen)requestAnimationFrame(()=>countrySearchRef.current?.focus());},[isCountryOpen]);
 function openCountryPicker(){setCountrySearch('');setIsCountryOpen(true);}
 useEffect(()=>{(async()=>{try{const raw=localStorage.getItem('current_user');if(!raw){router.replace('/');return;}const u:UserData=JSON.parse(raw);const id=String(u.id||u.user_id||u.uid||'');if(!id){router.replace('/');return;}setUser(u);setName(u.fullName||u.full_name||'');setEmail(u.email||'');setCountry(u.country||'');setAvatar(u.avatar_url||'');const r=await fetch(`${url}/rest/v1/users?id=eq.${encodeURIComponent(id)}&select=id,full_name,email,role,country,avatar_url&limit=1`,{headers:authHeaders,cache:'no-store'});if(r.ok){const rows=await r.json();if(rows[0]){const p=rows[0];setName(p.full_name||u.fullName||'');setEmail(p.email||u.email||'');setCountry(p.country||'');setAvatar(p.avatar_url||'');setUser({...u,...p,fullName:p.full_name||u.fullName});}}}catch(e){setError('Could not load your profile.');}finally{setLoading(false);}})();},[router,url,authHeaders]);
 const updateLocal=(patch:Partial<UserData>)=>{const next={...(user||{}),...patch};setUser(next);try{localStorage.setItem('current_user',JSON.stringify(next));}catch{}};
 async function saveProfile(){setSaving(true);setMessage(null);setError(null);try{const id=String(user?.id||user?.user_id||user?.uid||'');const r=await fetch(`${url}/rest/v1/users?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...authHeaders,Prefer:'return=representation'},body:JSON.stringify({full_name:name.trim(),country:country.trim()||null,avatar_url:avatar||null})});if(!r.ok)throw new Error(await r.text());updateLocal({fullName:name.trim(),full_name:name.trim(),country:country.trim(),avatar_url:avatar});setMessage('Profile saved.');}catch(e){setError('Could not save your profile.');}finally{setSaving(false);}}
 async function uploadAvatar(file:File){setMessage(null);setError(null);if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))return setError('Use a JPG, PNG, WebP, or GIF image.');if(file.size>2*1024*1024)return setError('Profile pictures must be 2 MB or smaller.');const id=String(user?.id||user?.user_id||user?.uid||'');if(!id)return;setUploading(true);try{const ext=file.type.split('/')[1].replace('jpeg','jpg');const path=`${id}/avatar.${ext}`;const r=await fetch(`${url}/storage/v1/object/avatars/${encodeURIComponent(path)}`,{method:'POST',headers:{...authHeaders,'x-upsert':'true','Content-Type':file.type},body:file});if(!r.ok)throw new Error(await r.text());const publicUrl=`${url}/storage/v1/object/public/avatars/${path}?v=${Date.now()}`;setAvatar(publicUrl);await fetch(`${url}/rest/v1/users?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...authHeaders,Prefer:'return=minimal'},body:JSON.stringify({avatar_url:publicUrl})});updateLocal({avatar_url:publicUrl});setMessage('Profile picture updated.');}catch(e){setError('Could not upload the profile picture.');}finally{setUploading(false);}}
 async function changePassword(){setMessage(null);setError(null);if(newPassword.length<8)return setError('New password must be at least 8 characters.');if(newPassword!==confirmPassword)return setError('New passwords do not match.');setChangingPassword(true);try{const r=await fetch(`${url}/auth/v1/user`,{method:'PUT',headers:authHeaders,body:JSON.stringify({password:newPassword})});if(!r.ok)throw new Error(await r.text());setPassword('');setNewPassword('');setConfirmPassword('');setMessage('Password changed successfully.');}catch(e){setError('Could not change your password. Please sign in again and try again.');}finally{setChangingPassword(false);}}
 function clearLocalAuth(){localStorage.removeItem('current_user');localStorage.removeItem('supabase_access_token');localStorage.removeItem('supabase_refresh_token');localStorage.removeItem('supabase_user_id');localStorage.removeItem('eduquizlabs_remembered_session');}
 async function deleteAccount(){setDeleting(true);setError(null);try{const r=await fetch(`${url}/rest/v1/rpc/delete_my_account`,{method:'POST',headers:authHeaders,body:'{}'});if(!r.ok)throw new Error(await r.text());clearLocalAuth();router.replace('/');}catch(e){setError('Could not delete your account. Make sure you are signed in and try again.');setDeleting(false);}}
 function logout(){clearLocalAuth();router.replace('/');}
 if(loading)return <main className="flex min-h-screen items-center justify-center"><Loader2 className="size-7 animate-spin text-primary"/></main>;
 const role=(user?.role||'student').toLowerCase();
 return <main className="min-h-screen bg-muted/20 px-3 py-6 sm:px-6 sm:py-10"><div className="mx-auto max-w-3xl space-y-5">
   <div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>router.push(`/dashboard/${role}`)} aria-label="Back"><ArrowLeft/></Button><div><h1 className="text-2xl font-black tracking-tight sm:text-3xl">Settings</h1><p className="text-sm text-muted-foreground">Manage your EduQuizLabs account.</p></div></div>
   {(message||error)&&<div className={`rounded-xl border p-3 text-sm font-medium ${error?'border-red-500/20 bg-red-500/10 text-red-600':'border-emerald-500/20 bg-emerald-500/10 text-emerald-600'}`}>{error||message}</div>}
   <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-3"><User className="size-5 text-primary"/><div><h2 className="font-bold">Profile</h2><p className="text-xs text-muted-foreground">Your public account information.</p></div></div>
     <div className="mb-7 flex flex-col items-center gap-4 sm:flex-row"><div className="relative"><div className="flex size-28 items-center justify-center overflow-hidden rounded-full border-4 border-background bg-primary/10 text-3xl font-black text-primary shadow-lg">{avatar?<img src={avatar} alt="Profile" className="size-full object-cover"/>:(name||'U').charAt(0).toUpperCase()}</div><button type="button" onClick={()=>fileRef.current?.click()} disabled={uploading} className="absolute bottom-0 right-0 flex size-9 items-center justify-center rounded-full border-2 border-background bg-primary text-primary-foreground shadow" aria-label="Change profile picture">{uploading?<Loader2 className="size-4 animate-spin"/>:<Camera className="size-4"/>}</button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadAvatar(f);e.currentTarget.value='';}}/></div><div><p className="font-semibold">Profile picture</p><p className="text-sm text-muted-foreground">JPG, PNG, WebP, or GIF · maximum 2 MB</p></div></div>
     <div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label>Full name</Label><Input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></div><div className="space-y-2"><Label>Email</Label><div className="relative"><Mail className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={email} disabled className="pl-9"/></div><p className="text-xs text-muted-foreground">Email changes are disabled here.</p></div><div className="relative space-y-2" ref={countryDropdownRef}><Label>Country</Label><button type="button" onClick={openCountryPicker} className="flex h-11 w-full items-center justify-between rounded-md border border-input bg-card px-3 text-sm shadow-sm"><span className="flex items-center gap-2 truncate">{selectedCountryObj?<><img src={`https://flagcdn.com/24x18/${selectedCountryObj.code}.png`} alt="" className="h-3.5 w-5 rounded-sm object-cover"/><span>{selectedCountryObj.name}</span></>:<span className="text-muted-foreground">Select your country</span>}</span><ChevronDown size={16} className="text-muted-foreground"/></button>{isCountryOpen&&<div className="absolute left-0 top-full z-50 mt-1 w-full overflow-hidden rounded-md border border-border bg-card shadow-lg"><div className="border-b border-border bg-card p-2"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input ref={countrySearchRef} value={countrySearch} onChange={e=>setCountrySearch(e.target.value)} placeholder="Search country..." className="h-10 bg-background pl-9 pr-9" aria-label="Search country"/>{countrySearch&&<button type="button" onClick={()=>setCountrySearch('')} className="absolute right-2 top-1/2 -translate-y-1/2 rounded p-1 text-muted-foreground hover:bg-accent hover:text-foreground" aria-label="Clear country search"><X size={15}/></button>}</div></div><div className="max-h-60 overflow-y-auto">{filteredCountries.length>0?filteredCountries.map(c=><button key={c.code} type="button" onClick={()=>{setCountry(c.name);setCountrySearch('');setIsCountryOpen(false);}} className={`flex w-full items-center gap-3 px-3 py-2 text-left text-sm hover:bg-accent ${country===c.name?'bg-accent/50 font-medium':''}`}><img src={`https://flagcdn.com/24x18/${c.code}.png`} alt="" className="h-3.5 w-5 rounded-sm object-cover"/><span className="truncate">{c.name}</span></button>):<div className="px-3 py-6 text-center text-sm text-muted-foreground">No countries found.</div>}</div></div>}</div><div className="space-y-2"><Label>Role</Label><Input value={(user?.role||'student').replace(/^./,c=>c.toUpperCase())} disabled/></div></div><Button onClick={()=>void saveProfile()} disabled={saving} className="mt-6">{saving?<Loader2 className="size-4 animate-spin"/>:<Check className="size-4"/>} Save changes</Button>
   </section>
   <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-3"><Globe className="size-5 text-primary"/><div><h2 className="font-bold">Language</h2><p className="text-xs text-muted-foreground">Choose your preferred language.</p></div></div><div className="grid gap-2 sm:grid-cols-2">{languages.map((l:Language)=><button key={l.code} type="button" onClick={()=>setLanguage(l.code)} className={`flex items-center gap-3 rounded-xl border p-3 text-left text-sm font-semibold transition ${language===l.code?'border-primary bg-primary/10 text-primary':'hover:bg-muted'}`}><img src={flag(l.code)} alt="" className="h-3.5 w-5 rounded-sm"/><span className="flex-1">{l.nativeName}</span>{language===l.code&&<Check className="size-4"/>}</button>)}</div></section>
   <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-3"><Sun className="size-5 text-primary"/><div><h2 className="font-bold">Appearance</h2><p className="text-xs text-muted-foreground">Switch between light, dark, and system themes.</p></div></div><div className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">Theme</p><p className="text-xs text-muted-foreground">Use the theme control to change appearance.</p></div><ThemeToggle/></div></section>
   <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-3"><Shield className="size-5 text-primary"/><div><h2 className="font-bold">Privacy & Security</h2><p className="text-xs text-muted-foreground">Keep your account secure.</p></div></div><div className="space-y-5"><div className="flex items-center justify-between gap-4 rounded-xl border p-4"><div><p className="font-semibold">Change password</p><p className="text-xs text-muted-foreground">Set a new password while signed in.</p></div><KeyRound className="size-5 shrink-0 text-muted-foreground"/></div><div className="grid gap-4 sm:grid-cols-3"><Input type="password" placeholder="Current password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/><Input type="password" placeholder="New password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password"/><Input type="password" placeholder="Confirm new password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password"/></div><Button variant="outline" onClick={()=>void changePassword()} disabled={changingPassword}>{changingPassword?<Loader2 className="size-4 animate-spin"/>:<KeyRound className="size-4"/>} Change password</Button></div></section>
   <section className="rounded-2xl border border-destructive/30 bg-card p-5 shadow-sm sm:p-7"><div className="mb-5 flex items-center gap-3"><Trash2 className="size-5 text-destructive"/><div><h2 className="font-bold text-destructive">Danger zone</h2><p className="text-xs text-muted-foreground">Actions here can permanently affect your account.</p></div></div><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Delete your account</p><p className="text-sm text-muted-foreground">Permanently delete your account and associated profile data.</p></div><Button variant="destructive" onClick={()=>setDeleteOpen(true)}><Trash2 className="size-4"/> Delete account</Button></div></section>
   <Button variant="outline" onClick={logout} className="w-full"><LogOut className="size-4"/> Sign out</Button>
   {deleteOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl border bg-card p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-bold">Delete account?</h3><Button variant="ghost" size="icon" onClick={()=>setDeleteOpen(false)}><X className="size-4"/></Button></div><p className="text-sm text-muted-foreground">This permanently deletes your EduQuizLabs account. You will not be able to undo this action.</p><div className="mt-6 flex gap-3"><Button variant="outline" className="flex-1" onClick={()=>setDeleteOpen(false)} disabled={deleting}>Cancel</Button><Button variant="destructive" className="flex-1" onClick={()=>void deleteAccount()} disabled={deleting}>{deleting?<Loader2 className="size-4 animate-spin"/>:<Trash2 className="size-4"/>} Delete permanently</Button></div></div></div>}
 </div></main>;
}
